/*
 * Project: 02-exti-button External Interrupt Button
 * Platform: STM32F407VET6
 * Frequency: 168 MHz
 * Library: HAL Library
 * Function: PE4 button external interrupt triggered on falling edge; each press toggles PE0 LED state
 * Pin: LED -> PE0, Button -> PE4 (pulled down to GND, pull-up resistor keeps default high level)
 * Note: This main.c shows user code only. CubeMX-generated initialization code (MX_*_Init) should be regenerated via CubeMX.
 */
#include "main.h"
#include "stm32f4xx_hal.h"
#include <stdio.h>

/* ===== User macro definitions ===== */
#define LED_PIN     GPIO_PIN_0
#define LED_PORT    GPIOE
#define BUTTON_PIN  GPIO_PIN_4
#define BUTTON_PORT GPIOE

/* ===== Global variables ===== */
/* Interrupt flag: set to 1 when button pressed, cleared by main loop after handling */
volatile uint8_t g_buttonPressed = 0;

/* ===== External handle declarations (generated by CubeMX) ===== */

/* ===== Main function ===== */
int main(void)
{
    /* HAL library initialization */
    HAL_Init();
    /* Clock configuration 168MHz */
    SystemClock_Config();
    /* GPIO and NVIC initialization */
    MX_GPIO_Init();

    /* Initial state: LED off */
    HAL_GPIO_WritePin(LED_PORT, LED_PIN, GPIO_PIN_RESET);

    /* ===== User main loop ===== */
    while (1)
    {
        /* Check interrupt flag */
        if (g_buttonPressed)
        {
            /* Clear flag */
            g_buttonPressed = 0;
            /* Toggle LED */
            HAL_GPIO_TogglePin(LED_PORT, LED_PIN);
        }
        /* Light delay in main loop to reduce CPU usage */
        HAL_Delay(10);
    }
}

/* ===== EXTI external interrupt callback function ===== */
/* HAL library calls this callback when GPIO external interrupt triggers */
void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
    /* Check whether button pin PE4 triggered the interrupt */
    if (GPIO_Pin == BUTTON_PIN)
    {
        /* Set button flag and let main loop handle it (avoid time-consuming operations in ISR) */
        g_buttonPressed = 1;
    }
}

void Error_Handler(void)
{
    while (1)
    {
    }
}

/* System clock configuration (CubeMX-generated placeholder) */
void SystemClock_Config(void)
{
    /* HSE 8MHz -> PLL -> 168MHz, generated by CubeMX */
}
