/*
 * Project: 04-usart-printf USART printf Redirection
 * Platform: STM32F407VET6
 * Frequency: 168 MHz
 * Library: HAL Library
 * Function: USART1 (PA9 TX / PA10 RX) at 115200 baud, prints counter value every second via printf, redirects fputc to UART
 * Pin: PA9 TX, PA10 RX
 * Note: This main.c shows user code only. CubeMX-generated initialization code (MX_*_Init) should be regenerated via CubeMX.
 */
#include "main.h"
#include "stm32f4xx_hal.h"
#include <stdio.h>

/* ===== External handle declarations (generated by CubeMX) ===== */
extern UART_HandleTypeDef huart1;

/* ===== User macro definitions ===== */
#define PRINT_INTERVAL 1000   /* Print interval (ms) */

/* ===== printf redirection =====
 * Redirect fputc so printf outputs to USART1
 * Add -u _printf_float to build_flags in platformio.ini to support floating-point format
 */
#ifdef __GNUC__
/* GCC compiler uses __io_putchar */
int __io_putchar(int ch)
#else
int fputc(int ch, FILE *f)
#endif
{
    /* Send single byte via HAL UART */
    HAL_UART_Transmit(&huart1, (uint8_t *)&ch, 1, HAL_MAX_DELAY);
    return ch;
}

/* ===== Main function ===== */
int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_USART1_UART_Init();

    uint32_t count = 0;

    /* Power-on prompt */
    printf("\r\n===== STM32F407 USART printf Test =====\r\n");

    /* ===== User main loop ===== */
    while (1)
    {
        /* Output counter value */
        printf("[%lu] Hello STM32F407! count = %lu\r\n", HAL_GetTick() / 1000, count++);
        HAL_Delay(PRINT_INTERVAL);
    }
}

void Error_Handler(void)
{
    while (1)
    {
    }
}

void SystemClock_Config(void)
{
    /* HSE 8MHz -> PLL -> 168MHz, generated by CubeMX */
}
