# ch13-18 questions (STM32 overview, dev env, HAL, GPIO/EXTI, Timer/PWM, USART)

# ===== ch13: STM32与Cortex-M4概述 =====
s("13", "STM32F407采用的CPU内核是？", ["Cortex-M4F", "Cortex-M3", "Cortex-A7", "Cortex-M0"], "A", "STM32F407基于Cortex-M4F内核，带硬件浮点单元(FPU)和DSP指令。")
s("13", "Cortex-M4相比Cortex-M3增加的主要特性是？", ["DSP指令和FPU", "更多中断", "更大Flash", "更高主频"], "A", "Cortex-M4增加了DSP指令集和可选硬件浮点单元(FPU)。")
s("13", "STM32F407的最高工作主频是？", ["168MHz", "72MHz", "120MHz", "180MHz"], "A", "STM32F407最高主频168MHz，提供210 DMIPS算力。")
s("13", "Cortex-M4的浮点运算单元(FPU)支持的数据类型是？", ["单精度浮点(float)", "双精度浮点", "半精度", "定点"], "A", "Cortex-M4F内置单精度FPU，符合IEEE 754标准。")
s("13", "STM32F4系列的数据总线宽度是？", ["32位", "16位", "8位", "64位"], "A", "STM32基于32位ARM Cortex-M内核，数据总线32位。")
s("13", "Cortex-M4的流水线级数是？", ["3级", "5级", "8级", "2级"], "A", "Cortex-M4采用3级流水线+分支预测。")
s("13", "STM32F407内部SRAM容量是？", ["192KB", "64KB", "20KB", "512KB"], "A", "STM32F407有192KB SRAM(128KB主+64KB在CCM RAM区)。")
s("13", "STM32F407的Flash程序存储器容量是？", ["1MB", "512KB", "256KB", "2MB"], "A", "STM32F407ZG/VG有1MB Flash。")
s("13", "Cortex-M4的Thumb-2指令集特点是？", ["16位和32位混合", "纯32位", "纯16位", "纯64位"], "A", "Thumb-2是16/32位混合指令集，兼顾代码密度和性能。")
s("13", "STM32的中断控制器是？", ["NVIC", "GIC", "8259", "PIC"], "A", "Cortex-M系列内置NVIC(嵌套向量中断控制器)，支持240个中断和16级优先级。")
m("13", "Cortex-M4内核的特点包括？", ["哈佛架构", "32位RISC", "支持DSP指令", "集成NVIC"], ["A","B","C","D"], "M4采用哈佛架构、32位RISC、支持DSP、集成NVIC。")
m("13", "STM32F407的主要外设包括？", ["ADC", "定时器", "USART", "DMA"], ["A","B","C","D"], "STM32F407集成ADC、定时器、USART、DMA等丰富外设。")
m("13", "STM32系列的主要分类有？", ["主流型(STM32F1)", "高性能型(STM32F4)", "超低功耗型(STM32L)", "无线型(STM32WB)"], ["A","B","C","D"], "STM32分主流、高性能、超低功耗、无线等系列。")
m("13", "Cortex-M4的DSP指令可用于？", ["FFT运算", "数字滤波", "矩阵运算", "PID控制"], ["A","B","C","D"], "DSP指令加速FFT、滤波、矩阵、PID等数学运算。")
m("13", "STM32F407相比STM32F103的优势有？", ["更高主频", "带FPU", "更多SRAM", "支持DSP指令"], ["A","B","C","D"], "F407主频168MHz>F103的72MHz，有FPU、192KB SRAM、DSP指令。")
j("13", "STM32F407的CCM RAM区只能由CPU访问，DMA不能访问。", True, "CCM(Core Coupled Memory)RAM紧耦合CPU，DMA无法访问该区域。")
j("13", "Cortex-M4的浮点运算单元可以处理双精度浮点数。", False, "M4F的FPU只支持单精度(float)运算，双精度需软件模拟。")
j("13", "STM32的中断向量表可以重定位到其他地址。", True, "通过设置SCB->VTOR寄存器可将中断向量表重定位到RAM或Flash其他位置。")
j("13", "Thumb-2指令集是纯16位指令集。", False, "Thumb-2是16位和32位混合指令集，兼顾代码密度和性能。")
t("13", "简述Cortex-M4内核的主要特性和应用领域。", "特性：1)32位RISC哈佛架构；2)3级流水线+分支预测；3)Thumb-2指令集(16/32位混合)；4)集成NVIC嵌套向量中断控制器；5)可选FPU单精度浮点单元；6)DSP指令集扩展；7)MPU内存保护单元；8)支持位带操作。应用：电机控制、数字电源、音频处理、传感器融合、IoT网关等需要实时性和信号处理的领域。", "M4在M3基础上增加DSP和FPU，适合信号处理。")
t("13", "比较STM32F103和STM32F407的主要区别。", "区别：1)内核——F103为Cortex-M3(72MHz)，F407为Cortex-M4F(168MHz)；2)FPU——F103无FPU，F407有单精度FPU；3)DSP——F103无DSP指令，F407有；4)SRAM——F103约20-64KB，F407有192KB(含64KB CCM)；5)Flash——F103最大1MB，F407最大1MB；6)外设——F407更多高级定时器、ADC更高速、带USB OTG/以太网MAC；7)总线——F407有更宽的总线矩阵和多DMA流。", "F407是F103的高性能升级版。")
t("13", "简述STM32的存储器映射结构。", "STM32采用统一32位地址空间(4GB)，分为：1)0x00000000-0x1FFFFFFF: Code区(Flash镜像+系统存储)；2)0x20000000-0x3FFFFFFF: SRAM区(位带区+位带别名)；3)0x40000000-0x5FFFFFFF: 外设区(APB/AHB外设寄存器+位带别名)；4)0x60000000-0x9FFFFFFF: FSMC外部存储器；5)0xA0000000+: 系统级寄存器(NVIC/SCB等)。可重定位向量表到Code或SRAM区。", "统一地址空间简化编程。")

# ===== ch14: STM32开发环境 =====
s("14", "STM32CubeMX的主要功能是？", ["图形化配置外设并生成代码", "编译程序", "烧录固件", "PCB设计"], "A", "CubeMX用于图形化配置时钟/外设/中间件并生成初始化代码框架。")
s("14", "STM32 HAL库的全称是？", ["Hardware Abstraction Layer", "High-level API Library", "Hardware Access Layer", "Host Application Layer"], "A", "HAL=硬件抽象层，提供统一API屏蔽硬件差异。")
s("14", "STM32开发中常用的IDE有？", ["STM32CubeIDE", "Keil MDK", "IAR EWARM", "以上都是"], "D", "STM32开发支持CubeIDE、Keil MDK、IAR等多种IDE。")
s("14", "STM32程序烧录常用的调试器是？", ["ST-Link", "J-Link", "DAP-Link", "以上均可"], "D", "ST-Link、J-Link、CMSIS-DAP均可用于STM32烧录和调试。")
s("14", "HAL库中GPIO初始化使用的函数是？", ["HAL_GPIO_Init()", "GPIO_Init()", "gpio_init()", "HAL_GPIO_Write()"], "A", "HAL_GPIO_Init()配合GPIO_InitTypeDef结构体初始化GPIO。")
s("14", "STM32CubeMX生成的工程默认使用的时钟源是？", ["HSE外部晶振", "HSI内部RC", "LSE", "LSI"], "A", "CubeMX默认配置HSE外部晶振为主时钟源，可通过PLL倍频达到高主频。")
s("14", "STM32 HAL库中延时函数HAL_Delay()的参数单位是？", ["毫秒(ms)", "微秒(us)", "秒(s)", "纳秒(ns)"], "A", "HAL_Delay()基于SysTick定时器，参数单位为毫秒。")
s("14", "STM32系统启动文件startup_*.s中定义的堆栈在？", ["SRAM", "Flash", "CCM", "外部RAM"], "A", "启动文件中定义的Stack_Size和Heap_Size分配在SRAM中。")
s("14", "HAL库中串口发送数据的函数是？", ["HAL_UART_Transmit()", "UART_Send()", "HAL_UART_Write()", "printf()"], "A", "HAL_UART_Transmit()用于阻塞式发送，_IT中断发送，_DMA为DMA发送。")
s("14", "STM32的System Configuration模块(SYSCFG)用于？", ["外部中断线映射等系统配置", "时钟配置", "Flash编程", "电源管理"], "A", "SYSCFG用于EXTI线映射、内存重映射、以太网PHY接口选择等系统级配置。")
m("14", "STM32CubeMX可以配置的内容包括？", ["时钟树", "GPIO引脚", "外设参数", "中间件(FreeRTOS/FATFS)"], ["A","B","C","D"], "CubeMX可配置时钟、GPIO、外设、中间件等，一键生成代码。")
m("14", "STM32 HAL库的特点有？", ["统一API跨芯片", "支持中断/DMA/阻塞三种模式", "自动初始化外设", "完全替代寄存器操作"], ["A","B","C"], "HAL统一API、支持三种操作模式、CubeMX自动初始化；不完全替代寄存器(性能敏感场景仍需寄存器)。")
m("14", "STM32开发中常用的调试方式有？", ["SWD单步调试", "printf串口打印", "逻辑分析仪", "示波器"], ["A","B","C","D"], "SWD调试、printf、逻辑分析仪、示波器均为常用手段。")
m("14", "STM32的启动模式有？", ["从Flash启动", "从系统存储器启动(ISP)", "从SRAM启动", "从待机唤醒"], ["A","B","C"], "BOOT0/BOOT1选择Flash/系统存储器/SRAM三种启动模式。")
m("14", "STM32工程中常用的文件类型有？", [".c源文件", ".h头文件", ".s启动文件", ".ld链接脚本"], ["A","B","C","D"], "工程含.c/.h/.s启动文件、链接脚本等。")
j("14", "STM32 HAL库完全替代了寄存器操作，不再需要直接操作寄存器。", False, "HAL库简化开发，但性能/时序敏感场景仍需直接寄存器操作。")
j("14", "STM32CubeIDE基于Eclipse开发，免费使用。", True, "STM32CubeIDE是ST基于Eclipse+CDT的免费IDE，集成CubeMX。")
j("14", "HAL_Delay()函数可以在中断服务函数中安全使用。", False, "HAL_Delay基于SysTick轮询，在中断中调用会阻塞中断导致问题。")
j("14", "STM32的SWD调试接口只需要2根线(SWCLK+SWDIO)即可调试。", True, "SWD只需SWCLK和SWDIO两根信号线(加GND/VREF)，比JTAG省线。")
t("14", "简述使用STM32CubeMX+HAL库创建工程的基本流程。", "流程：1)打开CubeMX选择芯片型号(如STM32F407ZGT6)；2)在Pinout视图配置外设引脚(GPIO/UART/Timer等)；3)在Clock Configuration配置时钟树(HSE/PLL/分频倍频)；4)在Configuration标签设置外设参数(波特率/模式等)；5)选择中间件(FreeRTOS/FATFS等)；6)Project Manager设置工程名/IDE/堆栈大小；7)点击GENERATE CODE生成工程；8)在IDE中打开，在用户代码区编写应用逻辑(USER CODE BEGIN/END之间)。", "CubeMX+HAL是STM32标准开发流程。")
t("14", "简述STM32的时钟树结构和配置方法。", "时钟源：HSI(内部16MHz RC)、HSE(外部晶振4-26MHz)、LSE(32.768kHz)、LSI(32kHz RC)。时钟树：HSE->PLL倍频->SYSCLK(最高168MHz)->AHB分频->HCLK->APB1(42MHz)/APB2(84MHz)。配置方法：在CubeMX Clock Configuration页面设置输入频率、PLL参数(M/N/P/Q分频倍频)，自动计算各总线频率。注意APB1<=42MHz, APB2<=84MHz, USB需48MHz。", "时钟树是STM32配置核心。")
t("14", "简述STM32三种启动模式的区别和用途。", "1)从Flash启动(BOOT0=0)：从用户Flash地址0x08000000执行程序，正常工作模式；2)从系统存储器启动(BOOT0=1,BOOT1=0)：从ST出厂的Bootloader(0x1FFF0000)启动，通过USART1/USB进行ISP串口下载，用于空芯片烧录；3)从SRAM启动(BOOT0=1,BOOT1=1)：从SRAM 0x20000000执行代码，用于调试和临时运行，断电丢失。", "BOOT引脚选择不同启动源。")

# ===== ch15: STM32 HAL库 =====
s("15", "HAL_GPIO_WritePin()函数的参数不包括？", ["GPIO端口", "引脚号", "引脚状态", "时钟频率"], "D", "HAL_GPIO_WritePin(GPIOx, GPIO_PIN, GPIO_PIN_SET/RESET)，无需时钟频率参数。")
s("15", "HAL_GPIO_TogglePin()的作用是？", ["翻转引脚电平", "读取引脚状态", "设置引脚高电平", "初始化引脚"], "A", "TogglePin翻转指定引脚电平，常用于LED闪烁。")
s("15", "HAL库中读取GPIO输入电平的函数是？", ["HAL_GPIO_ReadPin()", "HAL_GPIO_GetPin()", "GPIO_Read()", "HAL_GPIO_Input()"], "A", "HAL_GPIO_ReadPin(GPIOx, GPIO_PIN)返回GPIO_PIN_SET或GPIO_PIN_RESET。")
s("15", "HAL_UART_Receive_IT()的特点是？", ["中断方式接收", "阻塞等待接收", "DMA方式接收", "轮询接收"], "A", "_IT后缀表示中断方式，非阻塞，接收完成后触发回调HAL_UART_RxCpltCallback。")
s("15", "CMSIS的全称是？", ["Cortex Microcontroller Software Interface Standard", "Cortex Microcontroller System Interface", "Common Microcontroller Software Interface", "Cortex Microcontroller Standard Interface"], "A", "CMSIS是ARM定义的Cortex微控制器软件接口标准，提供内核访问层。")
s("15", "HAL_GPIO_Init()中GPIO_MODE_IT_RISING表示？", ["上升沿外部中断", "推挽输出", "复用功能", "模拟输入"], "A", "IT_RISING=上升沿触发外部中断，IT_FALLING=下降沿，EVT=事件。")
s("15", "HAL库初始化GPIO前必须先？", ["使能GPIO时钟", "配置中断", "设置波特率", "初始化串口"], "A", "STM32外设默认时钟关闭，使用前必须通过__HAL_RCC_GPIOx_CLK_ENABLE()使能时钟。")
s("15", "HAL_Delay()函数底层依赖的定时器是？", ["SysTick", "TIM1", "TIM2", "RTC"], "A", "HAL_Delay基于SysTick定时器中断递减计数，1ms精度。")
s("15", "HAL库中回调函数HAL_UART_RxCpltCallback的调用时机是？", ["接收完成时", "发送完成时", "错误时", "空闲时"], "A", "HAL_UART_Receive_IT()完成指定长度接收后调用HAL_UART_RxCpltCallback回调。")
s("15", "HAL_StatusTypeDef的返回值HAL_OK表示？", ["操作成功", "操作失败", "忙", "错误"], "A", "HAL函数返回HAL_OK(成功)/HAL_ERROR(错误)/HAL_BUSY(忙)/HAL_TIMEOUT(超时)。")
m("15", "HAL库提供的外设驱动包括？", ["HAL_GPIO", "HAL_UART", "HAL_TIM", "HAL_ADC"], ["A","B","C","D"], "HAL提供GPIO/UART/TIM/ADC等全系列外设驱动。")
m("15", "HAL库中UART的三种收发方式是？", ["阻塞(Polling)", "中断(Interrupt)", "DMA", "回调"], ["A","B","C"], "阻塞_Transmit/中断_Transmit_IT/DMA_Transmit_DMA三种方式。")
m("15", "CMSIS提供的功能包括？", ["内核寄存器访问", "中断控制(NVIC)", "系统时钟配置", "DSP指令封装"], ["A","B","C","D"], "CMSIS提供内核寄存器、NVIC、时钟、DSP、RTOS接口等标准化访问。")
m("15", "HAL库GPIO_InitTypeDef的字段有？", ["Pin", "Mode", "Pull", "Speed"], ["A","B","C","D"], "GPIO_InitTypeDef含Pin/Mode/Pull/Speed/Alternate等字段。")
m("15", "使用HAL库开发STM32需要的文件包括？", ["stm32f4xx_hal.h", "stm32f4xx_hal_conf.h", "startup_stm32f407xx.s", "system_stm32f4xx.c"], ["A","B","C","D"], "工程需HAL主头文件、配置文件、启动文件、系统初始化文件。")
j("15", "HAL库函数比直接寄存器操作代码执行效率更高。", False, "HAL库封装增加了函数调用开销，执行效率略低于直接寄存器操作。")
j("15", "HAL_GPIO_Init()可以同时初始化同一端口的多个引脚。", True, "GPIO_InitTypeDef.Pin可设为多个引脚的或值(如GPIO_PIN_0|GPIO_PIN_1)同时初始化。")
j("15", "HAL_UART_Transmit()是阻塞式发送，发送完成前函数不返回。", True, "HAL_UART_Transmit()阻塞等待发送完成，超时由参数指定。")
j("15", "HAL库的回调函数名是固定的，用户通过重写实现自定义逻辑。", True, "HAL库使用__weak声明弱定义回调函数，用户重写同名函数覆盖。")
t("15", "简述HAL库中GPIO初始化的完整步骤和代码。", "步骤：1)使能GPIO时钟——__HAL_RCC_GPIOx_CLK_ENABLE()；2)定义GPIO_InitTypeDef结构体；3)设置Pin(引脚号)、Mode(模式:输入/输出/复用/模拟)、Pull(上拉/下拉/无)、Speed(速度等级)；4)调用HAL_GPIO_Init(&GPIOx, &init)初始化。示例：GPIO_InitTypeDef gi; gi.Pin=GPIO_PIN_5; gi.Mode=GPIO_MODE_OUTPUT_PP; gi.Pull=GPIO_NOPULL; gi.Speed=GPIO_SPEED_FREQ_HIGH; HAL_GPIO_Init(GPIOA, &gi);", "GPIO初始化三步：使能时钟、设结构体、调用Init。")
t("15", "比较HAL库UART的三种收发方式。", "1)阻塞式(HAL_UART_Transmit/Receive)：函数等待完成才返回，简单但CPU占用高，适合少量数据；2)中断式(HAL_UART_Transmit_IT/Receive_IT)：非阻塞，启动后立即返回，完成触发回调HAL_UART_RxCpltCallback，适合中等数据量；3)DMA式(HAL_UART_Transmit_DMA/Receive_DMA)：完全由DMA搬运数据，CPU几乎不参与，适合大量数据传输，效率最高。", "三种方式按效率从低到高：阻塞<中断<DMA。")
t("15", "简述HAL库回调函数机制及其使用方法。", "机制：HAL库用__weak关键字声明弱定义回调函数(如HAL_UART_RxCpltCallback)，弱定义版本为空函数。用户在应用代码中定义同名函数覆盖弱定义，HAL库在中断/完成时自动调用。使用方法：1)在用户代码中定义void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)；2)判断huart->Instance==USART1确定来源；3)编写处理逻辑(如重新启动接收HAL_UART_Receive_IT)。常见回调：HAL_GPIO_EXTI_Callback(外部中断)、HAL_TIM_PeriodElapsedCallback(定时器溢出)、HAL_UART_RxCpltCallback(接收完成)。", "弱定义回调实现灵活扩展。")

# ===== ch16: GPIO与外部中断 =====
s("16", "STM32的GPIO输出模式GPIO_MODE_OUTPUT_PP表示？", ["推挽输出", "开漏输出", "复用推挽", "复用开漏"], "A", "OUTPUT_PP=推挽输出，OUTPUT_OD=开漏输出，AF_PP=复用推挽，AF_OD=复用开漏。")
s("16", "STM32GPIO开漏输出模式需要？", ["外接上拉电阻", "外接下拉电阻", "内部上拉", "不需要电阻"], "A", "开漏输出无内部上拉驱动高电平，需外接上拉电阻才能输出高电平。")
s("16", "STM32的外部中断EXTI线0对应哪个GPIO引脚？", ["PA0/PB0/PC0等端口的第0脚", "仅PA0", "仅PB0", "所有引脚"], "A", "EXTI线0映射到所有端口的第0脚(如PA0/PB0/PC0...)，通过SYSCFG选择。")
s("16", "STM32的EXTI外部中断触发方式GPIO_MODE_IT_FALLING表示？", ["下降沿触发", "上升沿触发", "双边沿触发", "高电平触发"], "A", "IT_FALLING=下降沿中断，IT_RISING=上升沿，IT_RISING_FALLING=双边沿。")
s("16", "STM32F4的NVIC支持多少级抢占优先级？", ["最多16级", "4级", "8级", "2级"], "A", "NVIC支持4位优先级，可配置为0-16级抢占优先级(通过HAL_NVIC_SetPriorityGrouping设置分组)。")
s("16", "STM32中HAL_NVIC_SetPriority()的作用是？", ["设置中断优先级", "使能中断", "清除中断标志", "触发中断"], "A", "HAL_NVIC_SetPriority(IRQn, 抢占优先级, 子优先级)设置指定中断的优先级。")
s("16", "STM32外部中断回调函数名是？", ["HAL_GPIO_EXTI_Callback()", "HAL_EXTI_Callback()", "GPIO_IRQHandler()", "HAL_GPIO_IRQ()"], "A", "外部中断回调函数为HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)。")
s("16", "STM32的GPIO复用功能(AF)模式用于？", ["外设功能引脚", "普通I/O", "模拟输入", "调试"], "A", "复用模式将引脚连接到片上外设(USART/SPI/I2C/Timer等)。")
s("16", "STM32的GPIO速度参数GPIO_SPEED_FREQ_HIGH对应频率约为？", ["50MHz", "2MHz", "10MHz", "100MHz"], "A", "LOW=2MHz, MEDIUM=12.5MHz, HIGH=50MHz, VERY_HIGH=100MHz(F4)。")
s("16", "STM32F4一个GPIO端口有几位？", ["16位", "8位", "32位", "12位"], "A", "每个GPIO端口有16个引脚(PIN0-PIN15)，对应16位寄存器。")
m("16", "STM32 GPIO的工作模式有？", ["输入", "通用输出", "复用功能", "模拟"], ["A","B","C","D"], "GPIO四大模式：输入、输出、复用(AF)、模拟(ADC/DAC)。")
m("16", "STM32 GPIO输出类型有？", ["推挽", "开漏", "复用推挽", "复用开漏"], ["A","B"], "输出类型分推挽(PP)和开漏(OD)，复用模式下也分AF_PP和AF_OD。")
m("16", "STM32外部中断EXTI的特点有？", ["支持23条中断线", "每条线映射到多端口同编号引脚", "支持上升/下降/双边沿", "可产生中断或事件"], ["A","B","C","D"], "EXTI支持23线、多端口映射、多种触发沿、中断/事件两种输出。")
m("16", "NVIC优先级分组(NVIC_PriorityGroup)的配置有？", ["Group0: 0位抢占+4位子优先级", "Group4: 4位抢占+0位子优先级", "Group2: 2位抢占+2位子优先级", "Group1: 1位抢占+3位子优先级"], ["A","B","C","D"], "4位优先级可分0-4位抢占，对应Group0-4。")
m("16", "STM32 GPIO常用的上下拉配置有？", ["GPIO_NOPULL", "GPIO_PULLUP", "GPIO_PULLDOWN", "GPIO_PULLBOTH"], ["A","B","C"], "GPIO支持无上下拉、上拉、下拉三种配置，无双向上下拉。")
j("16", "STM32的EXTI线0只能映射到PA0一个引脚。", False, "EXTI0可映射到PA0/PB0/PC0/PD0等同编号引脚，通过SYSCFG_EXTICR1选择。")
j("16", "STM32复位后所有GPIO默认为浮空输入模式。", True, "STM32复位后GPIO默认配置为浮空输入模式，所有时钟关闭。")
j("16", "NVIC优先级数字越大，优先级越高。", False, "STM32中优先级数字越小优先级越高(0最高)。")
j("16", "STM32的EXTI可配置为事件模式，不产生中断但可唤醒WFE。", True, "EXTI可配置为中断(EVT)或事件模式，事件模式通过WFE等待，不进入ISR。")
t("16", "简述STM32 GPIO的8种工作模式。", "8种模式：1)浮空输入(INPUT)；2)上拉输入(INPUT_PULLUP)；3)下拉输入(INPUT_PULLDOWN)；4)模拟输入(ANALOG, ADC/DAC)；5)开漏输出(OUTPUT_OD)；6)推挽输出(OUTPUT_PP)；7)复用开漏(AF_OD)；8)复用推挽(AF_PP)。输入模式用于读取外部信号，输出用于驱动外设，复用用于片上外设功能引脚，模拟用于ADC/DAC。", "8种模式覆盖所有应用场景。")
t("16", "简述STM32外部中断EXTI的配置步骤。", "步骤：1)使能GPIO时钟和SYSCFG时钟(__HAL_RCC_SYSCFG_CLK_ENABLE)；2)配置GPIO为输入模式(上拉/下拉/浮空)；3)调用HAL_GPIO_Init()初始化GPIO；4)使能SYSCFG并配置EXTI线映射(SYSCFG_EXTICR)；5)配置EXTI触发沿(上升/下降/双边沿)；6)设置NVIC优先级(HAL_NVIC_SetPriority)；7)使能NVIC中断(HAL_NVIC_EnableIRQ)；8)重写HAL_GPIO_EXTI_Callback回调函数处理中断；9)在回调中清除中断标志(__HAL_GPIO_EXTI_CLEAR_IT)。", "EXTI配置需GPIO+SYSCFG+NVIC三步。")
t("16", "解释STM32 NVIC优先级分组的概念和配置方法。", "STM32使用4位优先级，分为抢占优先级(Preemption)和子优先级(Subpriority)。分组：Group0=0位抢占+4位子(16级子优先级)；Group1=1+3(2级抢占8级子)；Group2=2+2(4+4)；Group3=3+1(8+2)；Group4=4+0(16级抢占)。抢占优先级高的中断可打断低的(嵌套)；同抢占不同子优先级不能嵌套，同时发生时子优先级高的先响应。配置：HAL_NVIC_SetPriorityGrouping(NVIC_PRIORITYGROUP_2)设分组；HAL_NVIC_SetPriority(IRQn, pre, sub)设各中断优先级。常用Group2(2位抢占+2位子)。", "优先级分组决定嵌套和响应顺序。")

# ===== ch17: 定时器与PWM =====
s("17", "STM32F4的定时器中属于高级定时器的是？", ["TIM1和TIM8", "TIM2和TIM5", "TIM3和TIM4", "TIM6和TIM7"], "A", "TIM1/TIM8为高级定时器，TIM2-5为通用定时器，TIM6/7为基本定时器。")
s("17", "STM32定时器输出PWM使用的工作模式是？", ["输出比较模式", "输入捕获模式", "编码器模式", "从模式"], "A", "PWM通过输出比较(OC)模式产生，配置CCR寄存器控制占空比。")
s("17", "STM32产生PWM的计数模式通常使用？", ["向上计数模式", "向下计数", "中心对齐", "以上均可"], "D", "向上/向下/中心对齐计数均可产生PWM，向上计数最常用。")
s("17", "PWM的占空比由哪个寄存器控制？", ["CCR(捕获/比较寄存器)", "ARR(自动重装)", "PSC(预分频)", "CR1"], "A", "占空比=CCR/ARR(向上计数)，ARR决定周期，CCR决定占空比。")
s("17", "STM32定时器的输入捕获功能用于？", ["测量外部信号频率/脉宽", "输出PWM", "产生中断", "驱动LED"], "A", "输入捕获在检测到边沿时记录计数器值，用于测量频率、周期、脉宽。")
s("17", "STM32定时器的ARR(自动重装载寄存器)决定？", ["定时器周期", "占空比", "分频系数", "中断优先级"], "A", "ARR决定计数上限(周期)，PSC决定时钟分频，CCR决定比较值(占空比)。")
s("17", "STM32F4高级定时器的互补输出通道有？", ["CH1/CH1N等3对互补", "仅CH1-4", "CH1-8", "无互补"], "A", "高级定时器支持CH1/CH1N、CH2/CH2N、CH3/CH3N三对互补输出，用于电机驱动。")
s("17", "PWM频率计算公式是？", ["f = TIM_CLK/((PSC+1)*(ARR+1))", "f=PSC*ARR", "f=TIM_CLK/ARR", "f=TIM_CLK*PSC"], "A", "PWM频率=定时器时钟/((预分频+1)*(自动重装值+1))。")
s("17", "STM32定时器中PSC(预分频器)的作用是？", ["降低计数时钟频率", "设置PWM占空比", "设置中断优先级", "控制输出极性"], "A", "PSC预分频将定时器输入时钟分频后作为计数时钟。")
s("17", "STM32高级定时器TIM1的刹车输入(BKIN)用于？", ["电机驱动故障保护", "PWM输出", "频率测量", "编码器接口"], "A", "BKIN刹车输入检测到有效电平时关闭PWM输出，保护功率器件。")
m("17", "STM32定时器的类型有？", ["高级定时器(TIM1/8)", "通用定时器(TIM2-5)", "基本定时器(TIM6/7)", "专用定时器(TIM9-14)"], ["A","B","C","D"], "STM32F4含高级/通用/基本/专用多类定时器。")
m("17", "STM32通用定时器的工作模式有？", ["输入捕获", "输出比较", "PWM生成", "编码器接口"], ["A","B","C","D"], "通用定时器支持捕获/比较/PWM/编码器等多种模式。")
m("17", "PWM输出的关键参数有？", ["频率", "占空比", "分辨率", "极性"], ["A","B","C","D"], "PWM由频率(ARR/PSC)、占空比(CCR)、分辨率(ARR位数)、极性(OC极性)决定。")
m("17", "STM32定时器输入捕获可测量的信号参数有？", ["频率", "占空比", "脉冲宽度", "相位差"], ["A","B","C","D"], "输入捕获可测频率、占空比、脉宽，双通道可测相位差。")
m("17", "高级定时器相比通用定时器的增强特性有？", ["互补输出", "死区时间插入", "刹车输入保护", "重复计数器"], ["A","B","C","D"], "高级定时器支持互补输出、死区、刹车、重复计数器，适合电机控制。")
j("17", "STM32基本定时器TIM6/TIM7不能产生PWM输出。", True, "基本定时器只有定时中断功能，无捕获/比较通道，不能产生PWM。")
j("17", "PWM的分辨率由ARR的值决定，ARR越大分辨率越高。", True, "分辨率=1/(ARR+1)，ARR越大占空比调节越精细。")
j("17", "STM32定时器的输入捕获只能捕获上升沿。", False, "输入捕获可配置为上升沿/下降沿/双边沿捕获。")
j("17", "高级定时器的死区时间是为了防止上下桥臂同时导通。", True, "死区时间在互补PWM切换间插入延时，防止功率管直通短路。")
t("17", "简述STM32定时器产生PWM的原理和配置步骤。", "原理：定时器在向上计数模式下，计数值从0递增到ARR；当计数值<CCR时输出一种电平，>=CCR时输出相反电平，从而产生方波。频率=TIM_CLK/((PSC+1)*(ARR+1))，占空比=CCR/(ARR+1)。配置步骤：1)使能定时器时钟；2)配置定时器基础参数(PSC/ARR/计数模式)；3)配置输出比较通道(OC模式为PWM1/PWM2, CCR值, 极性)；4)使能定时器主输出(高级定时器需MOE=1)；5)启动PWM输出HAL_TIM_PWM_Start()。", "PWM原理是计数器与比较寄存器配合。")
t("17", "计算STM32F407用TIM1产生20kHz PWM的PSC和ARR值(84MHz时钟)。", "TIM1挂载APB2(84MHz)。频率=TIM_CLK/((PSC+1)*(ARR+1))=20000。设PSC=0(不分频)，则ARR+1=84000000/20000=4200，ARR=4199。或PSC=83(84分频=1MHz)，ARR+1=1000000/20000=50，ARR=49(分辨率较低)。推荐PSC=0,ARR=4199，占空比调节范围0-4199，分辨率约0.024%。设CCR=2100得到50%占空比。", "PSC和ARR需平衡频率和分辨率。")
t("17", "简述STM32定时器输入捕获测量信号频率的原理。", "原理：1)配置定时器输入捕获为上升沿触发；2)两次上升沿之间计数差即为信号周期；3)频率=定时器时钟/计数值差。实现：使用两个捕获通道或DMA方式。方法一：配置CH1上升沿捕获，在中断中读取CCR值，两次捕获差值x时钟周期=信号周期。方法二：配置从模式为复位模式(上升沿复位计数器)，每次捕获自动重置，CCR直接为周期值。注意：高频信号需用预分频避免溢出，低频信号需增大ARR或使用预分频输入。", "输入捕获通过测量周期计算频率。")

# ===== ch18: USART串口通信 =====
s("18", "HAL库中阻塞式串口发送函数是？", ["HAL_UART_Transmit()", "HAL_UART_Transmit_IT()", "HAL_UART_Transmit_DMA()", "HAL_UART_Send()"], "A", "HAL_UART_Transmit()阻塞发送，_IT中断，_DMA为DMA方式。")
s("18", "STM32中printf重定向需要重写的函数是？", ["fputc()", "printf()", "main()", "HAL_UART_Transmit()"], "A", "重定向printf需重写fputc()函数，通过UART发送字符。")
s("18", "STM32 HAL库串口初始化结构体UART_InitTypeDef的字段不包括？", ["波特率", "数据位", "停止位", "GPIO速度"], "D", "UART_InitTypeDef含BaudRate/WordLength/StopBits/Parity/Mode/HwFlowCtl，无GPIO速度。")
s("18", "STM32 USART的波特率9600表示每秒传输？", ["约9600位", "9600字节", "9600帧", "9600Hz"], "A", "波特率9600表示每秒传输9600位(bit)，实际有效字节需扣除起止位。")
s("18", "STM32串口空闲中断(IDLE)的用途是？", ["接收变长数据", "发送完成", "波特率错误", "奇偶校验错误"], "A", "空闲中断在接收完一帧后总线空闲时触发，用于判断变长数据帧结束。")
s("18", "STM32 USART的DMA接收方式中，数据直接从？", ["USART->DR到内存", "内存到USART->DR", "USART到Flash", "内存到内存"], "A", "DMA接收将USART数据寄存器(DR)数据直接搬运到内存缓冲区，不需CPU干预。")
s("18", "STM32F4的USART1挂载在哪个总线？", ["APB2(最高84MHz)", "APB1(42MHz)", "AHB(168MHz)", "无固定总线"], "A", "USART1/6在APB2(84MHz)，USART2/3/4/5在APB1(42MHz)，影响最大波特率。")
s("18", "HAL_UART_Receive_IT()接收完成后调用的回调函数是？", ["HAL_UART_RxCpltCallback()", "HAL_UART_RxCallback()", "HAL_UART_IRQHandler()", "HAL_UART_ErrorCallback()"], "A", "_IT接收完成触发HAL_UART_RxCpltCallback，DMA完成同样调用此回调。")
s("18", "STM32串口通信中奇偶校验设置为EVEN表示？", ["偶校验", "奇校验", "无校验", "硬件校验"], "A", "EVEN=偶校验，ODD=奇校验，NONE=无校验。")
s("18", "STM32 USART初始化中数据位9位时，奇偶校验位占用？", ["数据位第9位", "额外1位", "停止位", "无影响"], "A", "M=1(9位数据)且使能奇偶校验时，校验位占用第9位，实际数据7位。")
m("18", "STM32 USART的三种收发方式有？", ["阻塞式", "中断式", "DMA式", "查询式"], ["A","B","C"], "HAL提供阻塞/中断/DMA三种收发方式，查询式即阻塞式。")
m("18", "STM32 printf重定向的步骤包括？", ["重写fputc函数", "在fputc中调用HAL_UART_Transmit", "在工程中勾选Use MicroLIB", "包含stdio.h"], ["A","B","C","D"], "重定向printf需重写fputc+HAL发送+MicroLIB+包含头文件。")
m("18", "STM32串口接收变长数据的常用方法有？", ["空闲中断(IDLE)", "固定帧头帧尾+超时", "DMA+空闲中断", "硬件CRC校验"], ["A","B","C"], "空闲中断、帧头帧尾、DMA+IDLE是变长数据接收常用方法。")
m("18", "USART初始化参数包括？", ["波特率", "数据位", "停止位", "校验位"], ["A","B","C","D"], "UART_InitTypeDef含BaudRate/WordLength/StopBits/Parity等参数。")
m("18", "STM32串口通信中常见错误有？", ["波特率不匹配", "TX/RX接反", "电平不匹配(3.3V/5V)", "DMA配置错误"], ["A","B","C","D"], "以上均为串口通信常见问题。")
j("18", "STM32串口使用DMA接收时CPU完全不参与数据搬运。", True, "DMA直接在外设和内存间搬运数据，CPU不参与。")
j("18", "HAL_UART_Transmit()发送时如果超时未发送完成会返回HAL_TIMEOUT。", True, "HAL函数有超时参数，超时返回HAL_TIMEOUT。")
j("18", "STM32的USART和UART功能完全相同。", False, "USART支持同步模式(含时钟SCLK)，UART仅异步模式，功能不完全相同。")
j("18", "使用printf重定向时必须勾选Use MicroLIB选项。", False, "MicroLIB是可选的，不勾选时需避免半主机模式(添加#pragma import(__use_no_semihosting)等)。")
t("18", "编写STM32 printf重定向的完整代码。", "代码：#include <stdio.h>; #ifdef __GNUC__; #define PUTCHAR_PROTOTYPE int __io_putchar(int ch); #else; #define PUTCHAR_PROTOTYPE int fputc(int ch, FILE *f); #endif; PUTCHAR_PROTOTYPE { HAL_UART_Transmit(&huart1, (uint8_t*)&ch, 1, HAL_MAX_DELAY); return ch; }。在Keil中还需在Options->Target勾选Use MicroLIB。", "printf重定向核心是重写fputc。")
t("18", "简述STM32使用DMA+空闲中断接收变长数据的方案。", "方案：1)初始化UART和DMA(DMA_RX通道，外设到内存，循环模式)；2)启动HAL_UART_Receive_DMA(&huart, rx_buf, BUF_SIZE)；3)使能UART空闲中断__HAL_UART_ENABLE_IT(&huart, UART_IT_IDLE)；4)在UART中断中检测IDLE标志：if(__HAL_UART_GET_FLAG(&huart, UART_FLAG_IDLE)){清除标志; 计算接收长度=BUF_SIZE-__HAL_DMA_GET_COUNTER(hdma_rx); 处理数据; 重启DMA接收;}。优点：接收任意长度数据，CPU不参与搬运，效率高。", "DMA+IDLE是变长数据接收最佳方案。")
t("18", "简述STM32串口波特率误差对通信的影响及允许范围。", "影响：波特率误差导致采样点偏移，累积后采样到错误数据位。允许范围：误差应小于+-2.5%(8数据位+1停止位时)，即每帧10位的采样误差不超过半个位周期。常见误差来源：1)晶振频率偏差(12MHz晶振在9600波特率误差约0.16%)；2)整除误差(12MHz/9600不为整数)；3)波特率寄存器四舍五入。解决：使用11.0592MHz晶振(标准波特率误差为0)或使用内部HSI校准。", "波特率误差需控制在2.5%以内。")
