# ch19-23 questions (ADC/DAC, SPI/I2C, DMA/RTC, FreeRTOS, STM32 comprehensive)

# ===== ch19: ADC与DAC =====
s("19", "STM32F4的ADC分辨率是？", ["12位", "8位", "10位", "16位"], "A", "STM32F4 ADC为12位，可配置6/8/10/12位分辨率。")
s("19", "STM32F4 ADC的转换时间最短约为？", ["3us(2.4MSPS)", "10us", "1ms", "100ns"], "A", "12位分辨率下最短转换时间约3us(ADCCLK=36MHz, 12+采样周期)。")
s("19", "STM32F4有几个ADC？", ["3个(ADC1/2/3)", "1个", "2个", "4个"], "A", "STM32F407有3个独立ADC，可独立或双重/三重模式使用。")
s("19", "STM32 ADC的转换模式中单次转换是指？", ["触发一次转换一次", "连续转换", "扫描多通道", "DMA传输"], "A", "单次转换：每次触发转换一次后停止；连续转换：自动重复转换。")
s("19", "HAL库启动ADC转换的函数是？", ["HAL_ADC_Start()", "HAL_ADC_Read()", "HAL_ADC_Get()", "HAL_ADC_Convert()"], "A", "HAL_ADC_Start()启动转换，HAL_ADC_PollForConversion()等待完成，HAL_ADC_GetValue()读取结果。")
s("19", "STM32 ADC的参考电压(VREF+)通常是？", ["3.3V", "5V", "1.2V", "2.5V"], "A", "STM32F4 ADC参考电压VREF+通常接VDDA=3.3V，转换值=输入电压/3.3x4095。")
s("19", "STM32F4 DAC的分辨率是？", ["12位", "8位", "10位", "16位"], "A", "STM32F4有2路12位DAC，可输出模拟电压。")
s("19", "ADC转换值0对应输入电压是？", ["0V", "3.3V", "1.65V", "VREF/2"], "A", "ADC线性转换：0V->0，VREF+(3.3V)->4095(12位)。")
s("19", "STM32 ADC的扫描模式(Scan Mode)用于？", ["多通道自动扫描", "单通道重复", "提高精度", "降低功耗"], "A", "扫描模式自动按序列转换多个通道，配合DMA可自动存储结果。")
s("19", "STM32 ADC的采样时间(Sampling Time)影响？", ["转换精度和速度", "参考电压", "通道数", "分辨率"], "A", "采样时间越长，源阻抗允许越大，精度越高但速度越慢。")
m("19", "STM32F4 ADC的特点有？", ["12位分辨率", "3个独立ADC", "支持双重/三重模式", "最高2.4MSPS"], ["A","B","C","D"], "F4 ADC为12位/3个/支持多重模式/2.4MSPS。")
m("19", "STM32 ADC的工作模式有？", ["单次转换", "连续转换", "扫描模式", "间断模式"], ["A","B","C","D"], "ADC支持单次/连续/扫描/间断四种模式。")
m("19", "STM32 ADC触发转换的源有？", ["软件触发", "定时器触发", "外部中断EXTI", "ADC自身"], ["A","B","C"], "ADC可由软件/定时器TRGO/外部EXTI线触发，无ADC自身触发。")
m("19", "STM32 DAC的特点有？", ["12位分辨率", "2路独立输出", "支持DMA", "可产生波形"], ["A","B","C","D"], "DAC为12位/2路/支持DMA/可产生三角波噪声波。")
m("19", "提高ADC采样精度的方法有？", ["增加采样时间", "软件多次采样平均", "硬件滤波", "校准ADC"], ["A","B","C","D"], "增加采样时间、软件滤波、硬件RC滤波、ADC校准均可提高精度。")
j("19", "STM32 ADC的输入电压不能超过VREF+。", True, "ADC输入电压范围为0~VREF+(通常3.3V)，超过可能损坏芯片。")
j("19", "STM32 DAC输出可以直接驱动扬声器。", False, "DAC输出电流能力有限(约数mA)，驱动扬声器需外接功放。")
j("19", "STM32 ADC使用DMA传输可以自动采集多通道数据到内存。", True, "ADC扫描模式+DMA可自动将多通道转换结果存入内存数组。")
j("19", "ADC采样时间设置为3个ADC时钟周期时仍然能保证12位精度。", False, "12位精度需足够采样时间(通常>=15个周期)，3周期精度不足。")
t("19", "简述STM32 ADC的配置步骤和单通道采样代码。", "步骤：1)使能GPIO和ADC时钟；2)配置GPIO为模拟模式(GPIO_MODE_ANALOG)；3)配置ADC通道(通道号、序列、采样时间)；4)配置ADC参数(分辨率、对齐、扫描模式、连续模式、触发源)；5)HAL_ADC_Init()初始化；6)HAL_ADC_ConfigChannel()配置通道；7)HAL_ADC_Start()启动；8)HAL_ADC_PollForConversion()等待完成；9)HAL_ADC_GetValue()读取结果。计算电压=ADC值x3.3/4095。", "ADC配置需GPIO+ADC参数+通道设置。")
t("19", "简述STM32 ADC多通道DMA采集的方案。", "方案：1)配置ADC为扫描模式(ScanMode=ENABLE)、连续转换(ContinuousMode=ENABLE)；2)设置通道序列(如CH0,CH1,CH2)；3)配置DMA(外设到内存、循环模式、数据宽度16位)；4)启动HAL_ADC_Start_DMA(&hadc, buffer, 3)；5)DMA自动将3个通道转换结果循环写入buffer数组。注意：buffer[0]=CH0, buffer[1]=CH1, buffer[2]=CH2(按序列顺序)；DMA循环模式自动覆盖旧数据。", "ADC+DMA实现多通道自动采集。")
t("19", "简述STM32 DAC产生正弦波的方案。", "方案：1)预计算正弦表——用Python生成一个完整周期的正弦波采样值数组(如256点)，值范围0~4095(12位DAC)；2)配置DAC输出通道(如DAC_OUT1=PA4)；3)配置定时器产生固定频率触发(TIMER触发DAC)；4)配置DAC为DMA模式(正弦表数据->DAC_DHR12R1)；5)启动HAL_DAC_Start_DMA()和定时器。输出频率=触发频率/点数。优点：不占用CPU，频率可调。", "DAC+DMA+定时器产生正弦波。")

# ===== ch20: SPI与I2C总线 =====
s("20", "HAL库中SPI发送和接收数据的函数是？", ["HAL_SPI_TransmitReceive()", "HAL_SPI_Write()", "HAL_SPI_Read()", "HAL_SPI_Transfer()"], "A", "HAL_SPI_TransmitReceive()同时发送和接收，SPI全双工。")
s("20", "SPI总线的CPOL=1,CPHA=1表示？", ["模式3(空闲高电平,第二边沿采样)", "模式0", "模式1", "模式2"], "A", "CPOL=1空闲高电平，CPHA=1第二边沿(下降沿)采样=模式3。")
s("20", "HAL_I2C_Master_Transmit()的参数中Device Address的格式是？", ["7位地址左移1位(含读写位)", "7位地址", "8位地址", "16位地址"], "A", "HAL库I2C地址需左移1位(如0x50<<1=0xA0)，最低位为读写位由库自动设。")
s("20", "SPI总线标准4线制中用于主设备输出从设备输入的是？", ["MOSI", "MISO", "SCK", "CS"], "A", "MOSI=Master Out Slave In(主出从入)，MISO=主入从出。")
s("20", "I2C总线标准速率是？", ["100kHz(标准)", "1MHz", "10MHz", "100MHz"], "A", "标准模式100kHz，快速模式400kHz，快速模式+1MHz，高速模式3.4MHz。")
s("20", "HAL库I2C读取AT24C02某地址数据的函数是？", ["HAL_I2C_Mem_Read()", "HAL_I2C_Master_Receive()", "HAL_I2C_Read()", "HAL_I2C_Mem_Write()"], "A", "HAL_I2C_Mem_Read()用于读取带内部地址的器件(如EEPROM)，自动发送器件地址+内存地址。")
s("20", "SPI总线的片选信号CS通常是？", ["低电平有效", "高电平有效", "边沿触发", "无有效电平"], "A", "多数SPI器件CS低电平有效，选中从设备。")
s("20", "I2C总线的应答信号ACK是？", ["接收方拉低SDA", "发送方拉低SDA", "主机拉低SCL", "从机拉低SCL"], "A", "ACK由接收方在第9个时钟拉低SDA表示应答，NACK为高电平。")
s("20", "STM32 SPI的数据帧大小可配置为？", ["8位或16位", "仅8位", "仅16位", "32位"], "A", "STM32F4 SPI支持8位或16位数据帧。")
s("20", "I2C总线上起始信号后第一个字节是？", ["器件地址+读写位", "寄存器地址", "数据", "校验"], "A", "I2C起始后发送7位器件地址+1位读写方向。")
m("20", "SPI总线的四种工作模式(CPOL/CPHA组合)有？", ["模式0(0,0)", "模式1(0,1)", "模式2(1,0)", "模式3(1,1)"], ["A","B","C","D"], "CPOL和CPHA组合产生4种SPI模式。")
m("20", "I2C总线的特点有？", ["两线制(SDA+SCL)", "支持多主设备", "7位/10位地址", "开漏输出需上拉"], ["A","B","C","D"], "I2C两线、多主、地址灵活、开漏需上拉。")
m("20", "SPI总线的特点有？", ["全双工", "同步通信", "主从模式", "需要CS片选"], ["A","B","C","D"], "SPI全双工同步、主从结构、需片选。")
m("20", "HAL库I2C的通信函数有？", ["HAL_I2C_Master_Transmit()", "HAL_I2C_Master_Receive()", "HAL_I2C_Mem_Write()", "HAL_I2C_Mem_Read()"], ["A","B","C","D"], "HAL I2C提供主收发、Mem读写(带内部地址)等函数。")
m("20", "SPI和I2C总线的区别有？", ["SPI全双工I2C半双工", "SPI需CS I2C用地址", "SPI速度通常更快", "I2C引脚更少"], ["A","B","C","D"], "SPI全双工需CS速度快；I2C半双工用地址引脚少。")
j("20", "I2C总线上SDA和SCL线都需要接上拉电阻。", True, "I2C开漏输出，SDA和SCL都需外接上拉(通常4.7K)。")
j("20", "SPI总线可以在同一总线上挂载多个从设备。", True, "SPI通过多个CS信号选择不同从设备，共享SCK/MOSI/MISO。")
j("20", "HAL_I2C_Mem_Read()适合读取EEPROM这种带内部寄存器地址的器件。", True, "Mem_Read自动发送器件地址+内部地址+读取，适合EEPROM/Sensor。")
j("20", "I2C总线的起始信号和停止信号都在SCL为高电平时产生。", True, "起始: SCL高时SDA下降沿；停止: SCL高时SDA上升沿。")
t("20", "比较SPI和I2C总线的主要区别。", "区别：1)引脚——SPI需4线(MOSI/MISO/SCK/CS)或多CS扩展，I2C仅2线(SDA/SCL)；2)通信——SPI全双工，I2C半双工；3)速度——SPI可达数十MHz，I2C标准100kHz/快速400kHz/高速3.4MHz；4)寻址——SPI用CS硬件片选，I2C用7/10位地址软件寻址；5)拓扑——SPI主从星型，I2C多主多从总线；6)复杂度——SPI简单无应答机制，I2C有ACK/NACK应答；7)适用场景——SPI高速大数据量(Flash/LCD)，I2C低速多器件挂载(Sensor/EEPROM)。", "SPI重速度I2C重灵活性。")
t("20", "简述使用HAL库I2C读取AT24C02 EEPROM指定地址数据的步骤。", "步骤：1)初始化I2C(I2C_InitTypeDef: ClockSpeed=100000, OwnAddress, 7位地址模式)；2)HAL_I2C_Init()；3)调用HAL_I2C_Mem_Read(&hi2c, DevAddress=0xA0(0x50<<1), MemAddress=目标地址, MemAddSize=I2C_MEMADD_SIZE_8BIT, pData=缓冲区, Size=读取字节数, Timeout=1000)；4)函数内部自动完成：起始->器件地址+写->内存地址->重启->器件地址+读->读取数据->停止。", "HAL_I2C_Mem_Read封装了EEPROM读取流程。")
t("20", "简述SPI四种工作模式的区别及选择原则。", "四种模式由CPOL(时钟极性)和CPHA(时钟相位)组合：模式0(CPOL=0,CPHA=0): 空闲低电平,第一边沿(上升沿)采样；模式1(0,1): 空闲低,第二边沿(下降沿)采样；模式2(1,0): 空闲高,第一边沿(下降沿)采样；模式3(1,1): 空闲高,第二边沿(上升沿)采样。选择原则：必须与从设备数据手册一致。常见器件：W25Q64 Flash用模式0或3，LCD OLED常用模式0或3。配置时在CubeMX或SPI_InitTypeDef中设CLKPolarity和CLKPhase。", "SPI模式必须与从设备匹配。")

# ===== ch21: DMA与RTC =====
s("21", "DMA的全称是？", ["Direct Memory Access", "Data Memory Access", "Direct Memory Allocation", "Data Management Access"], "A", "DMA=直接存储器访问，不需CPU干预搬运数据。")
s("21", "STM32F4有几个DMA控制器？", ["2个(DMA1和DMA2)", "1个", "3个", "4个"], "A", "STM32F407有DMA1(8流)和DMA2(8流)两个DMA控制器。")
s("21", "STM32 DMA数据传输方向不包括？", ["外设到内存", "内存到外设", "内存到内存", "外设到外设"], "D", "DMA支持外设到内存、内存到外设和内存到内存，不支持外设到外设直接传输。")
s("21", "STM32 RTC使用的时钟源通常是？", ["LSE(32.768kHz晶振)", "HSE", "HSI", "MSI"], "A", "RTC通常用LSE 32.768kHz外部晶振，精度高，低功耗模式下持续运行。")
s("21", "STM32 RTC的备份寄存器(BKP)在什么条件下会丢失数据？", ["VBAT断电", "复位", "掉电模式", "空闲模式"], "A", "RTC和BKP由VBAT域供电，主电源断开时VBAT保持，VBAT也断电才丢失。")
s("21", "HAL库启动DMA传输的函数是？", ["HAL_DMA_Start()", "HAL_DMA_Transmit()", "HAL_DMA_Begin()", "HAL_DMA_Send()"], "A", "HAL_DMA_Start()启动DMA传输(底层)，外设专用函数如HAL_UART_Transmit_DMA()封装了DMA启动。")
s("21", "STM32 DMA的传输模式有？", ["正常模式(单次)和循环模式", "仅正常", "仅循环", "突发模式"], "A", "正常模式传完停止，循环模式自动重复(适合连续ADC/UART采集)。")
s("21", "STM32F4的DMA流(DMA Stream)每个控制器有？", ["8个流", "4个", "16个", "2个"], "A", "每个DMA控制器有8个流(Stream0-7)，每个流可选择7个通道请求源。")
s("21", "RTC的BCD格式时间数据中0x59表示？", ["59秒", "59分钟", "95秒", "0x59=89秒"], "A", "BCD格式每4位表示一位十进制数，0x59=十进制59。")
s("21", "STM32 RTC闹钟功能可以触发？", ["中断唤醒", "DMA传输", "ADC转换", "SPI通信"], "A", "RTC闹钟可触发中断，在低功耗模式下唤醒MCU。")
m("21", "DMA数据传输方向有？", ["外设到内存(PERIPH_TO_MEMORY)", "内存到外设(MEMORY_TO_PERIPH)", "内存到内存(MEMORY_TO_MEMORY)", "外设到外设"], ["A","B","C"], "DMA支持三种方向，不支持外设到外设。")
m("21", "STM32 RTC的特点有？", ["日历功能(年月日时分秒)", "闹钟功能", "唤醒功能", "备份寄存器"], ["A","B","C","D"], "RTC含日历、闹钟A/B、唤醒、备份寄存器。")
m("21", "DMA的优先级设置有？", ["Very High", "High", "Medium", "Low"], ["A","B","C","D"], "DMA优先级分4级。")
m("21", "使用DMA的优势有？", ["减轻CPU负担", "提高数据吞吐量", "支持大批量传输", "降低功耗"], ["A","B","C","D"], "DMA减少CPU干预、提高效率、支持批量、降低功耗。")
m("21", "RTC可用的时钟源有？", ["LSE(32.768kHz)", "LSI(内部RC~32kHz)", "HSE分频", "MSI"], ["A","B","C"], "RTC可选LSE/LSI/HSE分频作为时钟源，LSE精度最高。")
j("21", "STM32 DMA内存到内存传输不需要外设请求信号。", True, "内存到内存模式由软件触发，不需外设请求，DMA自动搬运。")
j("21", "RTC的LSE晶振在主电源断电后由VBAT供电继续运行。", True, "RTC域由VBAT供电，主电源断开时VBAT保持RTC运行。")
j("21", "DMA循环模式下传输完成后会自动重新开始下一轮传输。", True, "循环模式(CIRCULAR)传输完成后自动重置计数器重新传输。")
j("21", "RTC只能使用LSE外部晶振作为时钟源。", False, "RTC可选LSE/LSI/HSE分频作为时钟源，LSE精度最高。")
t("21", "简述DMA的工作原理和优势。", "原理：DMA控制器独立于CPU，可直接控制总线进行外设到内存或内存到内存的数据搬运。当外设(USART/ADC/SPI)有数据时，向DMA发送请求，DMA获得总线控制权后自动搬运数据到指定内存地址，完成后产生中断通知CPU。优势：1)CPU不参与逐字节搬运，大幅减轻负担；2)数据传输速率高，接近总线带宽；3)可并行：CPU执行代码同时DMA搬运数据；4)支持大批量传输(如ADC多通道采集、串口接收)；5)降低系统功耗。", "DMA是数据搬运的高效方案。")
t("21", "简述STM32 RTC的配置步骤和日历设置。", "步骤：1)使能PWR时钟，允许访问备份域(PWR->CR |= DBP)；2)选择RTC时钟源(LSE)：__HAL_RCC_RTC_CONFIG(RCC_RTCCLKSOURCE_LSE)；3)使能LSE和RTC时钟；4)HAL_RTC_Init()初始化RTC(异步分频127,同步分频255)；5)设置时间HAL_RTC_SetTime(&hrtc, &sTime, RTC_FORMAT_BIN)；6)设置日期HAL_RTC_SetDate(&hrtc, &sDate, RTC_FORMAT_BIN)；7)读取时使用HAL_RTC_GetTime()和HAL_RTC_GetDate()。注意：读取时间后必须立即读日期(锁机制)。", "RTC需先开备份域访问权限。")
t("21", "简述DMA+ADC实现连续多通道采集的方案。", "方案：1)配置ADC为扫描模式(多通道序列)、连续转换模式；2)配置DMA2(DMA2_Stream0, Channel0对应ADC1)，方向外设到内存，循环模式，数据宽度16位(半字)；3)设置内存缓冲区大小=通道数(如3通道->3元素数组)；4)启动HAL_ADC_Start_DMA(&hadc1, (uint32_t*)adc_buffer, 3)；5)DMA自动将ADC1的3个通道转换结果循环写入buffer[0]=CH0, buffer[1]=CH1, buffer[2]=CH2。CPU只需读取buffer数组即可获得各通道最新ADC值，无需干预转换过程。", "ADC+DMA是连续采集的标准方案。")

# ===== ch22: FreeRTOS基础 =====
s("22", "FreeRTOS中创建任务使用的函数是？", ["xTaskCreate()", "task_create()", "osThreadNew()", "vTaskStart()"], "A", "xTaskCreate()创建任务并加入就绪列表，参数含任务函数/栈大小/参数/优先级/句柄。")
s("22", "FreeRTOS任务调度的基本原则是？", ["高优先级先执行", "先到先执行", "时间片轮转", "短任务优先"], "A", "FreeRTOS采用抢占式优先级调度，高优先级任务先执行，同优先级时间片轮转。")
s("22", "FreeRTOS中vTaskDelay()的参数单位是？", ["Tick(系统节拍)", "毫秒", "微秒", "秒"], "A", "vTaskDelay()参数为Tick数，可用pdMS_TO_TICKS(ms)转换。")
s("22", "FreeRTOS中二值信号量相当于？", ["互斥的0/1标志", "队列", "事件标志", "定时器"], "A", "二值信号量类似一个只有0/1的标志，用于任务同步或资源保护。")
s("22", "FreeRTOS中互斥量(Mutex)的特点是？", ["支持优先级继承", "不支持嵌套", "只能在中断中使用", "无等待超时"], "A", "Mutex支持优先级继承防止优先级反转，信号量不支持。")
s("22", "FreeRTOS任务优先级数字越大表示？", ["优先级越高", "优先级越低", "无影响", "不确定"], "A", "FreeRTOS中数字越大优先级越高(与NVIC相反)。")
s("22", "FreeRTOS队列(xQueue)用于？", ["任务间数据传递", "任务延时", "定时器管理", "内存分配"], "A", "队列是FreeRTOS任务间通信的主要机制，线程安全FIFO。")
s("22", "FreeRTOS启动调度器使用的函数是？", ["vTaskStartScheduler()", "osKernelStart()", "start_rtos()", "vTaskInit()"], "A", "vTaskStartScheduler()启动调度器，创建空闲和定时器任务后开始调度。")
s("22", "FreeRTOS中configTICK_RATE_HZ表示？", ["系统节拍频率", "任务数量", "优先级数", "栈大小"], "A", "configTICK_RATE_HZ设置节拍频率(如1000表示1ms一个tick)。")
s("22", "FreeRTOS临界区进入和退出使用的函数是？", ["taskENTER_CRITICAL()/taskEXIT_CRITICAL()", "disable()/enable()", "lock()/unlock()", "pause()/resume()"], "A", "taskENTER_CRITICAL()关中断进入临界区，taskEXIT_CRITICAL()开中断退出。")
m("22", "FreeRTOS任务状态有？", ["运行(Running)", "就绪(Ready)", "阻塞(Blocked)", "挂起(Suspended)"], ["A","B","C","D"], "FreeRTOS任务有运行/就绪/阻塞/挂起四种状态。")
m("22", "FreeRTOS任务间通信方式有？", ["队列(Queue)", "信号量(Semaphore)", "互斥量(Mutex)", "事件组(Event Group)"], ["A","B","C","D"], "FreeRTOS提供队列/信号量/互斥量/事件组等多种IPC机制。")
m("22", "FreeRTOS任务删除和延时的函数有？", ["vTaskDelete()", "vTaskDelay()", "vTaskDelayUntil()", "vTaskSuspend()"], ["A","B","C","D"], "vTaskDelete删除任务，vTaskDelay相对延时，vTaskDelayUntil绝对延时，vTaskSuspend挂起。")
m("22", "FreeRTOS配置项(config)有？", ["configTICK_RATE_HZ(节拍频率)", "configMAX_PRIORITIES(最大优先级)", "configTOTAL_HEAP_SIZE(堆大小)", "configUSE_PREEMPTION(抢占调度)"], ["A","B","C","D"], "FreeRTOS通过FreeRTOSConfig.h配置以上参数。")
m("22", "FreeRTOS内存管理方案有？", ["heap_1(只分配不释放)", "heap_2(最佳适配)", "heap_3(包装malloc)", "heap_4(合并相邻空闲块)"], ["A","B","C","D"], "FreeRTOS提供heap_1到heap_5五种内存管理方案。")
j("22", "FreeRTOS中同一优先级的多个任务采用时间片轮转调度。", True, "同优先级任务在时间片到期时轮转执行(需开启抢占式调度)。")
j("22", "FreeRTOS互斥量可以在中断服务函数中获取。", False, "Mutex有优先级继承机制，不可以在中断中获取(会阻塞)，中断中用信号量。")
j("22", "vTaskDelay(100)表示延时100个系统节拍(Tick)。", True, "vTaskDelay参数为Tick数，100个tick在1000Hz节拍下=100ms。")
j("22", "FreeRTOS中任务函数必须是一个无限循环。", True, "任务函数通常为while(1)无限循环，退出循环需调用vTaskDelete(NULL)删除自身。")
t("22", "简述FreeRTOS任务状态转换。", "四种状态：1)运行(Running)：正在执行，同一时刻只有一个任务运行；2)就绪(Ready)：可运行但未获得CPU，等待调度；3)阻塞(Blocked)：等待事件(延时/信号量/队列)，事件发生转就绪；4)挂起(Suspended)：被vTaskSuspend挂起，需vTaskResume恢复。转换：创建->就绪；就绪->运行(被调度)；运行->就绪(被抢占)；运行->阻塞(vTaskDelay/等待IPC)；阻塞->就绪(事件到达)；运行/就绪/阻塞->挂起(vTaskSuspend)；挂起->就绪(vTaskResume)。", "任务状态机是RTOS核心概念。")
t("22", "简述FreeRTOS中信号量、互斥量和队列的区别。", "1)信号量(Semaphore)：计数器，用于资源计数和同步。二值信号量(0/1)用于任务同步；计数信号量用于资源池管理。不可用于互斥(无优先级继承)。2)互斥量(Mutex)：特殊的二值信号量，支持优先级继承防止优先级反转，必须由获取它的任务释放。用于资源互斥访问(如共享外设)。3)队列(Queue)：FIFO数据结构，可传递任意类型数据，线程安全。用于任务间数据传递(如传感器数据、命令消息)。队列可同时实现同步(阻塞等待)和数据传递。", "信号量同步，Mutex互斥，队列传递数据。")
t("22", "编写一个FreeRTOS创建两个任务的示例代码框架。", "void Task1(void *arg) { while(1) { HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5); vTaskDelay(pdMS_TO_TICKS(500)); } } void Task2(void *arg) { while(1) { printf(\"Task2\\n\"); vTaskDelay(pdMS_TO_TICKS(1000)); } } int main(void) { HAL_Init(); SystemClock_Config(); MX_GPIO_Init(); MX_USART1_UART_Init(); xTaskCreate(Task1, \"Task1\", 128, NULL, 1, NULL); xTaskCreate(Task2, \"Task2\", 128, NULL, 2, NULL); vTaskStartScheduler(); while(1); }", "FreeRTOS任务创建三步：定义函数、xTaskCreate、启动调度器。")

# ===== ch23: STM32综合实验 =====
s("23", "STM32综合实验中常用的人机交互外设是？", ["OLED/LCD显示屏+按键", "仅LED", "仅蜂鸣器", "仅传感器"], "A", "综合实验通常使用显示屏+按键作为人机交互界面。")
s("23", "STM32项目中传感器数据采集常用接口是？", ["ADC或I2C/SPI", "仅GPIO", "仅UART", "仅USB"], "A", "模拟传感器用ADC，数字传感器用I2C/SPI总线。")
s("23", "STM32综合实验中printf调试输出通常通过？", ["UART串口", "USB", "SPI", "I2C"], "A", "printf重定向到UART串口是最常用的调试输出方式。")
s("23", "STM32F407驱动WS2812 RGB LED通常使用？", ["SPI+DMA或定时器PWM", "GPIO直接", "I2C", "UART"], "A", "WS2812需要精确时序(800kHz)，常用SPI DMA或PWM+DMA驱动。")
s("23", "STM32项目中进行无线通信常用的模块是？", ["ESP8266/蓝牙模块(USART)", "仅以太网", "仅USB", "仅CAN"], "A", "ESP8266/蓝牙模块通过UART与STM32通信，实现WiFi/蓝牙。")
s("23", "STM32项目中存储大量数据常用的外存是？", ["W25Q64 SPI Flash或SD卡", "仅内部Flash", "仅EEPROM", "仅SRAM"], "A", "W25Q64 SPI Flash(8MB)或SD卡用于大容量存储。")
s("23", "STM32项目中最常用的时间获取外设是？", ["RTC(实时时钟)", "SysTick", "定时器", "外部时钟"], "A", "RTC提供年月日时分秒日历信息，断电由VBAT保持。")
s("23", "STM32低功耗项目中常用的休眠模式是？", ["Stop模式", "Run模式", "Only-Run", "Active"], "A", "Stop模式功耗低且可快速唤醒(微秒级)，适合低功耗应用。")
s("23", "STM32驱动电机通常使用的定时器是？", ["高级定时器(TIM1/TIM8)", "基本定时器", "SysTick", "RTC"], "A", "高级定时器支持互补PWM和死区，适合电机驱动。")
s("23", "STM32项目中看门狗(IWDG)的作用是？", ["防止程序跑飞", "延时", "通信", "存储数据"], "A", "独立看门狗超时复位MCU，防止死机/跑飞，提高可靠性。")
m("23", "STM32综合实验中常用的显示器件有？", ["OLED(0.96寸)", "LCD1602", "TFT彩屏", "数码管"], ["A","B","C","D"], "OLED/LCD1602/TFT/数码管均为常用显示器件。")
m("23", "STM32项目中常用的传感器有？", ["DHT11温湿度", "MPU6050陀螺仪", "DS18B20温度", "BMP280气压"], ["A","B","C","D"], "以上传感器在STM32项目中常用。")
m("23", "STM32项目开发流程包括？", ["需求分析", "硬件选型", "软件架构设计", "测试验证"], ["A","B","C","D"], "完整流程：需求->选型->架构->编码->测试。")
m("23", "STM32调试常用手段有？", ["SWD单步调试", "printf串口打印", "逻辑分析仪", "示波器"], ["A","B","C","D"], "SWD/printf/逻辑分析仪/示波器均为常用调试手段。")
m("23", "STM32项目中提高可靠性的措施有？", ["启用看门狗(IWDG/WWDG)", "使用RTC备份关键参数", "添加CRC校验", "异常处理恢复"], ["A","B","C","D"], "看门狗/RTC备份/CRC校验/异常处理均提高可靠性。")
j("23", "STM32项目中可以使用FreeRTOS实现多任务并行处理。", True, "FreeRTOS提供任务调度，实现多任务并发执行。")
j("23", "STM32的ADC可以直接测量220V市电电压。", False, "ADC输入范围0-3.3V，测量高压需分压/隔离电路(互感器)。")
j("23", "STM32驱动WS2812 LED时必须使用精确的时序控制。", True, "WS2812时序要求严格(0码~0.4us高+0.85us低, 1码~0.8us高+0.45us低)。")
j("23", "STM32的Flash可以在运行时随意写入数据不需擦除。", False, "Flash写入前必须先擦除(按页/扇区)，且只能1写0不能0写1。")
t("23", "设计一个STM32环境监测系统，简述方案。", "方案：1)MCU——STM32F407ZGT6；2)传感器——DHT11(温湿度)、BMP280(气压I2C)、MQ-2(烟雾ADC)、PMS5003(颗粒物UART)；3)显示——0.96寸OLED(I2C)；4)通信——ESP8266 WiFi(UART)上传云平台；5)报警——蜂鸣器+LED；6)软件——FreeRTOS多任务(采集/显示/上传/报警)，队列传递数据。7)电源——5V USB供电，AMS1117-3.3转3.3V。", "环境监测系统综合多种传感器和通信。")
t("23", "简述STM32项目中FreeRTOS多任务架构设计。", "架构：1)采集任务(优先级3)——定时读取传感器数据存入数据队列；2)处理任务(优先级4)——从队列取数据处理(滤波/计算)存入显示队列；3)显示任务(优先级2)——从显示队列取数据刷新OLED；4)通信任务(优先级1)——定时上传数据到云平台；5)报警任务(优先级5)——监测阈值触发报警。队列用于任务间数据传递，信号量保护共享资源(I2C总线)，互斥量保护printf输出。", "多任务架构需合理分配优先级和IPC。")
t("23", "简述STM32项目从需求到部署的完整开发流程。", "流程：1)需求分析——明确功能/性能/成本/功耗要求；2)硬件选型——MCU型号/传感器/显示/通信模块/电源方案；3)原理图设计——各模块电路连接；4)PCB设计——布线/电源/地/信号完整性；5)软件架构——裸机或RTOS，模块划分；6)编码——CubeMX配置+HAL驱动+业务逻辑；7)单元测试——各模块功能验证；8)集成测试——系统联调；9)压力测试——长时间运行/边界条件；10)部署——烧录最终固件/现场调试。", "完整流程覆盖从需求到部署。")
