/*
 * Project: 10-smart-fan Smart Temperature-Controlled Fan
 * Platform: STM32F407VET6
 * Frequency: 168 MHz
 * Library: HAL Library
 * Function: Comprehensive project - DS18B20 temperature sensing + PWM speed control + OLED display + threshold button, simplified PID algorithm
 * Pin: DS18B20-PA1, PWM fan-PA6(TIM3_CH1), OLED-PB6/PB7(I2C1), Button-PE4, LED-PE0
 * Note: This main.c shows user code only. CubeMX-generated initialization code (MX_*_Init) should be regenerated via CubeMX.
 */
#include "main.h"
#include "stm32f4xx_hal.h"
#include <stdio.h>

/* ===== External handle declarations (generated by CubeMX) ===== */
extern TIM_HandleTypeDef htim3;
extern I2C_HandleTypeDef hi2c1;
extern UART_HandleTypeDef huart1;

/* ===== User macro definitions ===== */
/* DS18B20 one-wire pin */
#define DS18B20_PIN     GPIO_PIN_1
#define DS18B20_PORT    GPIOA
/* Fan PWM channel */
#define FAN_PWM_CH      TIM_CHANNEL_1
#define FAN_PWM_MAX     1000   /* ARR=1000 */
/* LED and button */
#define LED_PIN         GPIO_PIN_0
#define LED_PORT        GPIOE
#define BUTTON_PIN      GPIO_PIN_4
#define BUTTON_PORT     GPIOE
/* OLED */
#define OLED_ADDR       0x78
#define OLED_CMD        0x00
#define OLED_DAT        0x40

/* PID parameters */
#define PID_KP          20.0f
#define PID_KI          0.5f
#define PID_KD          5.0f

/* ===== Global variables ===== */
static uint8_t g_dqMode = 0; /* 0=input, 1=output */

/* ===== printf redirection ===== */
#ifdef __GNUC__
int __io_putchar(int ch)
#else
int fputc(int ch, FILE *f)
#endif
{
    HAL_UART_Transmit(&huart1, (uint8_t *)&ch, 1, HAL_MAX_DELAY);
    return ch;
}

/* ===== DS18B20 one-wire driver ===== */

/* Microsecond-level delay (approximate, loop delay at 168MHz) */
static void DS18B20_DelayUs(uint32_t us)
{
    /* At 168MHz each loop iteration is about 1/168us, multiplied by a factor for approximation */
    uint32_t i;
    for (i = 0; i < us * 14; i++)
    {
        __NOP();
    }
}

/* Set data line direction: 1=output, 0=input */
static void DS18B20_SetMode(uint8_t isOutput)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};
    GPIO_InitStruct.Pin = DS18B20_PIN;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    if (isOutput)
    {
        GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
        GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
    }
    else
    {
        GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
        GPIO_InitStruct.Pull = GPIO_PULLUP;
    }
    HAL_GPIO_DeInit(DS18B20_PORT, DS18B20_PIN);
    HAL_GPIO_Init(DS18B20_PORT, &GPIO_InitStruct);
    g_dqMode = isOutput;
}

/* Write one byte */
static void DS18B20_WriteByte(uint8_t data)
{
    uint8_t i;
    DS18B20_SetMode(1);
    for (i = 0; i < 8; i++)
    {
        /* Pull low to start write time slot */
        HAL_GPIO_WritePin(DS18B20_PORT, DS18B20_PIN, GPIO_PIN_RESET);
        DS18B20_DelayUs(2);
        /* Write 1: release bus; Write 0: keep low */
        if (data & 0x01)
        {
            HAL_GPIO_WritePin(DS18B20_PORT, DS18B20_PIN, GPIO_PIN_SET);
        }
        DS18B20_DelayUs(60);
        HAL_GPIO_WritePin(DS18B20_PORT, DS18B20_PIN, GPIO_PIN_SET);
        DS18B20_DelayUs(2);
        data >>= 1;
    }
}

/* Read one byte */
static uint8_t DS18B20_ReadByte(void)
{
    uint8_t data = 0;
    uint8_t i;
    for (i = 0; i < 8; i++)
    {
        DS18B20_SetMode(1);
        HAL_GPIO_WritePin(DS18B20_PORT, DS18B20_PIN, GPIO_PIN_RESET);
        DS18B20_DelayUs(2);
        HAL_GPIO_WritePin(DS18B20_PORT, DS18B20_PIN, GPIO_PIN_SET);
        DS18B20_SetMode(0);
        DS18B20_DelayUs(10);
        if (HAL_GPIO_ReadPin(DS18B20_PORT, DS18B20_PIN))
        {
            data |= (1 << i);
        }
        DS18B20_DelayUs(50);
    }
    return data;
}

/* Reset and detect presence pulse: returns 0 if detected, 1 if no response */
static uint8_t DS18B20_Reset(void)
{
    uint8_t presence;
    DS18B20_SetMode(1);
    HAL_GPIO_WritePin(DS18B20_PORT, DS18B20_PIN, GPIO_PIN_RESET);
    DS18B20_DelayUs(480);
    HAL_GPIO_WritePin(DS18B20_PORT, DS18B20_PIN, GPIO_PIN_SET);
    DS18B20_SetMode(0);
    DS18B20_DelayUs(70);
    /* Low level read indicates presence */
    presence = HAL_GPIO_ReadPin(DS18B20_PORT, DS18B20_PIN);
    DS18B20_DelayUs(410);
    return presence; /* 0=present, 1=none */
}

/* Read temperature (Celsius), returns -999 on failure */
float DS18B20_ReadTemp(void)
{
    uint8_t tempL, tempH;
    int16_t raw;

    if (DS18B20_Reset() != 0)
    {
        return -999.0f; /* No response */
    }
    DS18B20_WriteByte(0xCC); /* Skip ROM */
    DS18B20_WriteByte(0x44); /* Start temperature conversion */
    HAL_Delay(750);          /* 12-bit conversion requires 750ms */

    if (DS18B20_Reset() != 0)
    {
        return -999.0f;
    }
    DS18B20_WriteByte(0xCC); /* Skip ROM */
    DS18B20_WriteByte(0xBE); /* Read scratchpad */
    tempL = DS18B20_ReadByte();
    tempH = DS18B20_ReadByte();
    raw = (int16_t)((tempH << 8) | tempL);
    /* 12-bit resolution: 0.0625 C/LSB */
    return (float)raw * 0.0625f;
}

/* ===== OLED basic functions (same as project 07, simplified) ===== */
static void OLED_WriteCmd(uint8_t cmd)
{
    uint8_t buf[2] = {OLED_CMD, cmd};
    HAL_I2C_Master_Transmit(&hi2c1, OLED_ADDR, buf, 2, HAL_MAX_DELAY);
}

static void OLED_WriteDat(uint8_t dat)
{
    uint8_t buf[2] = {OLED_DAT, dat};
    HAL_I2C_Master_Transmit(&hi2c1, OLED_ADDR, buf, 2, HAL_MAX_DELAY);
}

static void OLED_Init(void)
{
    HAL_Delay(100);
    OLED_WriteCmd(0xAE);
    OLED_WriteCmd(0xD5); OLED_WriteCmd(0x80);
    OLED_WriteCmd(0xA8); OLED_WriteCmd(0x3F);
    OLED_WriteCmd(0xD3); OLED_WriteCmd(0x00);
    OLED_WriteCmd(0x40);
    OLED_WriteCmd(0x8D); OLED_WriteCmd(0x14);
    OLED_WriteCmd(0x20); OLED_WriteCmd(0x02);
    OLED_WriteCmd(0xA1);
    OLED_WriteCmd(0xC8);
    OLED_WriteCmd(0xDA); OLED_WriteCmd(0x12);
    OLED_WriteCmd(0x81); OLED_WriteCmd(0xCF);
    OLED_WriteCmd(0xD9); OLED_WriteCmd(0xF1);
    OLED_WriteCmd(0xDB); OLED_WriteCmd(0x40);
    OLED_WriteCmd(0xA4);
    OLED_WriteCmd(0xA6);
    OLED_WriteCmd(0xAF);
}

static void OLED_Clear(void)
{
    uint8_t page, col;
    for (page = 0; page < 8; page++)
    {
        OLED_WriteCmd(0xB0 + page);
        OLED_WriteCmd(0x00);
        OLED_WriteCmd(0x10);
        for (col = 0; col < 128; col++)
        {
            OLED_WriteDat(0x00);
        }
    }
}

static void OLED_SetCursor(uint8_t page, uint8_t col)
{
    OLED_WriteCmd(0xB0 + page);
    OLED_WriteCmd(col & 0x0F);
    OLED_WriteCmd(0x10 | (col >> 4));
}

/* 8x16 digit font 0-9 */
static const uint8_t font_8x16[10][16] = {
    {0x00,0x3C,0x42,0x42,0x42,0x42,0x42,0x42,0x42,0x42,0x42,0x42,0x3C,0x00,0x00,0x00},
    {0x00,0x08,0x18,0x28,0x08,0x08,0x08,0x08,0x08,0x08,0x08,0x08,0x3E,0x00,0x00,0x00},
    {0x00,0x3C,0x42,0x42,0x02,0x02,0x0C,0x30,0x40,0x40,0x40,0x40,0x7E,0x00,0x00,0x00},
    {0x00,0x3C,0x42,0x42,0x02,0x02,0x1C,0x02,0x02,0x42,0x42,0x42,0x3C,0x00,0x00,0x00},
    {0x00,0x04,0x0C,0x14,0x24,0x44,0x44,0x7E,0x04,0x04,0x04,0x04,0x04,0x00,0x00,0x00},
    {0x00,0x7E,0x40,0x40,0x40,0x40,0x7C,0x02,0x02,0x02,0x42,0x42,0x3C,0x00,0x00,0x00},
    {0x00,0x3C,0x42,0x40,0x40,0x40,0x7C,0x42,0x42,0x42,0x42,0x42,0x3C,0x00,0x00,0x00},
    {0x00,0x7E,0x42,0x02,0x04,0x04,0x08,0x08,0x10,0x10,0x10,0x10,0x10,0x00,0x00,0x00},
    {0x00,0x3C,0x42,0x42,0x42,0x42,0x3C,0x42,0x42,0x42,0x42,0x42,0x3C,0x00,0x00,0x00},
    {0x00,0x3C,0x42,0x42,0x42,0x42,0x3E,0x02,0x02,0x02,0x42,0x42,0x3C,0x00,0x00,0x00}
};

/* Display integer */
static void OLED_ShowNumber(uint8_t page, uint8_t col, uint32_t num)
{
    char buf[12];
    int len = sprintf(buf, "%lu", num);
    int i, j;
    for (i = 0; i < len; i++)
    {
        uint8_t digit = buf[i] - '0';
        OLED_SetCursor(page, col + i * 8);
        for (j = 0; j < 8; j++) OLED_WriteDat(font_8x16[digit][j]);
        OLED_SetCursor(page + 1, col + i * 8);
        for (j = 8; j < 16; j++) OLED_WriteDat(font_8x16[digit][j]);
    }
}

/* ===== PID controller struct ===== */
typedef struct {
    float setpoint;   /* Setpoint */
    float Kp, Ki, Kd; /* PID coefficients */
    float integral;   /* Integral accumulator */
    float lastError;  /* Last error */
} PID_Controller;

/* PID compute: returns control output (0~1000 range for PWM) */
static float PID_Compute(PID_Controller *pid, float current)
{
    float error = pid->setpoint - current;  /* Error: setpoint - current */
    pid->integral += error;
    /* Integral clamping to prevent integral windup */
    if (pid->integral > 200.0f) pid->integral = 200.0f;
    if (pid->integral < -200.0f) pid->integral = -200.0f;
    float derivative = error - pid->lastError;
    pid->lastError = error;
    /* PID output = Kp*e + Ki*integral(e) + Kd*de/dt */
    float output = pid->Kp * error + pid->Ki * pid->integral + pid->Kd * derivative;
    /* Clamp output to PWM range 0~1000 */
    if (output < 0) output = 0;
    if (output > FAN_PWM_MAX) output = FAN_PWM_MAX;
    return output;
}

/* ===== Main function ===== */
int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_TIM3_Init();
    MX_I2C1_Init();
    MX_USART1_UART_Init();

    /* Start fan PWM */
    HAL_TIM_PWM_Start(&htim3, FAN_PWM_CH);

    /* Initialize OLED */
    OLED_Init();
    OLED_Clear();

    /* PID initialization */
    PID_Controller pid = {
        .setpoint = 30.0f,  /* Initial threshold 30 C */
        .Kp = PID_KP,
        .Ki = PID_KI,
        .Kd = PID_KD,
        .integral = 0,
        .lastError = 0
    };

    /* Threshold levels array */
    const float thresholds[] = {28.0f, 30.0f, 32.0f, 34.0f};
    const uint8_t numThresholds = sizeof(thresholds) / sizeof(thresholds[0]);
    uint8_t thresholdIdx = 1; /* Default 30 C */
    pid.setpoint = thresholds[thresholdIdx];

    uint8_t lastBtnState = 1;
    uint32_t lastBtnTime = 0;

    printf("\r\n===== Smart Fan System =====\r\n");
    printf("PID: Kp=%.1f Ki=%.1f Kd=%.1f\r\n", pid.Kp, pid.Ki, pid.Kd);

    /* ===== Main loop ===== */
    while (1)
    {
        /* 1. Read temperature */
        float temp = DS18B20_ReadTemp();

        /* 2. Button detection (threshold switching) */
        uint8_t btnState = HAL_GPIO_ReadPin(BUTTON_PORT, BUTTON_PIN);
        if (lastBtnState == 1 && btnState == 0)
        {
            /* Debounce: read again after 50ms */
            if (HAL_GetTick() - lastBtnTime > 50)
            {
                thresholdIdx = (thresholdIdx + 1) % numThresholds;
                pid.setpoint = thresholds[thresholdIdx];
                printf("Threshold changed to %.1f C\r\n", pid.setpoint);
                lastBtnTime = HAL_GetTick();
            }
        }
        lastBtnState = btnState;

        /* 3. PID compute and output PWM */
        float pwmValue = 0;
        if (temp >= -100.0f) /* Temperature valid */
        {
            pwmValue = PID_Compute(&pid, temp);
            __HAL_TIM_SET_COMPARE(&htim3, FAN_PWM_CH, (uint16_t)pwmValue);

            /* Fan running indicator: LED on when temp > threshold */
            if (temp > pid.setpoint)
            {
                HAL_GPIO_WritePin(LED_PORT, LED_PIN, GPIO_PIN_SET);
            }
            else
            {
                HAL_GPIO_WritePin(LED_PORT, LED_PIN, GPIO_PIN_RESET);
            }
        }

        /* 4. UART debug output */
        printf("Temp: %.2fC, Threshold: %.1fC, PWM: %.0f\r\n",
               temp, pid.setpoint, pwmValue);

        /* 5. OLED display temperature and threshold */
        OLED_SetCursor(0, 0);
        if (temp >= 0 && temp < 100)
        {
            /* Display integer part of temperature */
            OLED_ShowNumber(0, 0, (uint32_t)(temp + 0.5f));
        }
        OLED_SetCursor(2, 0);
        OLED_ShowNumber(2, 0, (uint32_t)pid.setpoint);

        /* 6. Sampling period 1 second */
        HAL_Delay(1000);
    }
}

void Error_Handler(void)
{
    while (1)
    {
    }
}

void SystemClock_Config(void)
{
    /* HSE 8MHz -> PLL -> 168MHz, generated by CubeMX */
}
