/*
 * Project: 07-i2c-oled I2C OLED Display
 * Platform: STM32F407VET6
 * Frequency: 168 MHz
 * Library: HAL Library
 * Function: I2C1 (PB6 SCL / PB7 SDA) drives SSD1306 OLED to display "Hello STM32" and counter
 * Pin: SCL-PB6, SDA-PB7
 * Note: This main.c shows user code only. CubeMX-generated initialization code (MX_*_Init) should be regenerated via CubeMX.
 */
#include "main.h"
#include "stm32f4xx_hal.h"
#include <stdio.h>

/* ===== External handle declarations (generated by CubeMX) ===== */
extern I2C_HandleTypeDef hi2c1;

/* ===== User macro definitions ===== */
/* SSD1306 OLED I2C address (0x3C << 1 = 0x78) */
#define OLED_ADDR       0x78
/* Control byte: Co=0, D/C=0 (command) */
#define OLED_CMD        0x00
/* Control byte: Co=0, D/C=1 (data) */
#define OLED_DAT        0x40

/* OLED display parameters */
#define OLED_WIDTH      128
#define OLED_HEIGHT     64
#define OLED_PAGES      8

/* ===== SSD1306 low-level command functions ===== */

/* Write a single command */
void OLED_WriteCmd(uint8_t cmd)
{
    uint8_t buf[2] = {OLED_CMD, cmd};
    HAL_I2C_Master_Transmit(&hi2c1, OLED_ADDR, buf, 2, HAL_MAX_DELAY);
}

/* Write a single data byte */
void OLED_WriteDat(uint8_t dat)
{
    uint8_t buf[2] = {OLED_DAT, dat};
    HAL_I2C_Master_Transmit(&hi2c1, OLED_ADDR, buf, 2, HAL_MAX_DELAY);
}

/* ===== SSD1306 initialization sequence ===== */
void OLED_Init(void)
{
    HAL_Delay(100); /* Wait for power-up to stabilize */
    OLED_WriteCmd(0xAE); /* Turn off display */
    OLED_WriteCmd(0xD5); OLED_WriteCmd(0x80); /* Set display clock divide ratio */
    OLED_WriteCmd(0xA8); OLED_WriteCmd(0x3F); /* Set multiplex ratio (1/64) */
    OLED_WriteCmd(0xD3); OLED_WriteCmd(0x00); /* Set display offset */
    OLED_WriteCmd(0x40); /* Set start line */
    OLED_WriteCmd(0x8D); OLED_WriteCmd(0x14); /* Enable charge pump */
    OLED_WriteCmd(0x20); OLED_WriteCmd(0x02); /* Set page addressing mode */
    OLED_WriteCmd(0xA1); /* Segment remap */
    OLED_WriteCmd(0xC8); /* COM scan direction */
    OLED_WriteCmd(0xDA); OLED_WriteCmd(0x12); /* COM pin hardware configuration */
    OLED_WriteCmd(0x81); OLED_WriteCmd(0xCF); /* Set contrast */
    OLED_WriteCmd(0xD9); OLED_WriteCmd(0xF1); /* Set pre-charge period */
    OLED_WriteCmd(0xDB); OLED_WriteCmd(0x40); /* Set VCOMH voltage */
    OLED_WriteCmd(0xA4); /* Output follows RAM content */
    OLED_WriteCmd(0xA6); /* Normal display (non-inverted) */
    OLED_WriteCmd(0xAF); /* Turn on display */
}

/* Clear screen */
void OLED_Clear(void)
{
    uint8_t page, col;
    for (page = 0; page < OLED_PAGES; page++)
    {
        OLED_WriteCmd(0xB0 + page);    /* Set page address */
        OLED_WriteCmd(0x00);           /* Column low address */
        OLED_WriteCmd(0x10);           /* Column high address */
        for (col = 0; col < OLED_WIDTH; col++)
        {
            OLED_WriteDat(0x00);       /* Write 0 to clear */
        }
    }
}

/* Set cursor position */
void OLED_SetCursor(uint8_t page, uint8_t col)
{
    OLED_WriteCmd(0xB0 + page);
    OLED_WriteCmd(col & 0x0F);
    OLED_WriteCmd(0x10 | (col >> 4));
}

/* ===== 8x16 font (simplified, digits 0-9 only) ===== */
/* Digit font, each character is 8 columns wide and 2 pages tall */
static const uint8_t font_8x16[10][16] = {
    {0x00,0x3C,0x42,0x42,0x42,0x42,0x42,0x42,0x42,0x42,0x42,0x42,0x3C,0x00,0x00,0x00}, /* 0 */
    {0x00,0x08,0x18,0x28,0x08,0x08,0x08,0x08,0x08,0x08,0x08,0x08,0x3E,0x00,0x00,0x00}, /* 1 */
    {0x00,0x3C,0x42,0x42,0x02,0x02,0x0C,0x30,0x40,0x40,0x40,0x40,0x7E,0x00,0x00,0x00}, /* 2 */
    {0x00,0x3C,0x42,0x42,0x02,0x02,0x1C,0x02,0x02,0x42,0x42,0x42,0x3C,0x00,0x00,0x00}, /* 3 */
    {0x00,0x04,0x0C,0x14,0x24,0x44,0x44,0x7E,0x04,0x04,0x04,0x04,0x04,0x00,0x00,0x00}, /* 4 */
    {0x00,0x7E,0x40,0x40,0x40,0x40,0x7C,0x02,0x02,0x02,0x42,0x42,0x3C,0x00,0x00,0x00}, /* 5 */
    {0x00,0x3C,0x42,0x40,0x40,0x40,0x7C,0x42,0x42,0x42,0x42,0x42,0x3C,0x00,0x00,0x00}, /* 6 */
    {0x00,0x7E,0x42,0x02,0x04,0x04,0x08,0x08,0x10,0x10,0x10,0x10,0x10,0x00,0x00,0x00}, /* 7 */
    {0x00,0x3C,0x42,0x42,0x42,0x42,0x3C,0x42,0x42,0x42,0x42,0x42,0x3C,0x00,0x00,0x00}, /* 8 */
    {0x00,0x3C,0x42,0x42,0x42,0x42,0x3E,0x02,0x02,0x02,0x42,0x42,0x3C,0x00,0x00,0x00}  /* 9 */
};

/* Display number at specified position (simplified) */
void OLED_ShowNumber(uint8_t page, uint8_t col, uint32_t num)
{
    char buf[12];
    int len = sprintf(buf, "%lu", num);
    int i;
    for (i = 0; i < len; i++)
    {
        uint8_t digit = buf[i] - '0';
        OLED_SetCursor(page, col + i * 8);
        int j;
        for (j = 0; j < 8; j++)
        {
            OLED_WriteDat(font_8x16[digit][j]);
        }
        OLED_SetCursor(page + 1, col + i * 8);
        for (j = 8; j < 16; j++)
        {
            OLED_WriteDat(font_8x16[digit][j]);
        }
    }
}

/* ===== Main function ===== */
int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_I2C1_Init();

    /* Initialize OLED */
    OLED_Init();
    OLED_Clear();

    uint32_t count = 0;

    /* ===== User main loop ===== */
    while (1)
    {
        /* Display counter at page 0, column 0 */
        OLED_SetCursor(0, 0);
        /* Displaying "Hello STM32" requires complex font; simplified here to show numeric counter */
        OLED_ShowNumber(0, 0, count);
        count++;
        HAL_Delay(1000);
    }
}

void Error_Handler(void)
{
    while (1)
    {
    }
}

void SystemClock_Config(void)
{
    /* HSE 8MHz -> PLL -> 168MHz, generated by CubeMX */
}
