/*
 * Project: 08-rtc-clock RTC Clock
 * Platform: STM32F407VET6
 * Frequency: 168 MHz
 * Library: HAL Library
 * Function: Configure RTC calendar, print current time via USART1 every second, includes HAL_RTC_GetTime/GetDate
 * Pin: USART1 -> PA9/PA10, VBAT connected to 3V
 * Note: This main.c shows user code only. CubeMX-generated initialization code (MX_*_Init) should be regenerated via CubeMX.
 */
#include "main.h"
#include "stm32f4xx_hal.h"
#include <stdio.h>

/* ===== External handle declarations (generated by CubeMX) ===== */
extern RTC_HandleTypeDef hrtc;
extern UART_HandleTypeDef huart1;

/* ===== User macro definitions ===== */
#define PRINT_INTERVAL 1000   /* Print interval (ms) */

/* ===== printf redirection ===== */
#ifdef __GNUC__
int __io_putchar(int ch)
#else
int fputc(int ch, FILE *f)
#endif
{
    HAL_UART_Transmit(&huart1, (uint8_t *)&ch, 1, HAL_MAX_DELAY);
    return ch;
}

/* ===== Main function ===== */
int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_RTC_Init();
    MX_USART1_UART_Init();

    RTC_TimeTypeDef sTime;
    RTC_DateTypeDef sDate;

    printf("\r\n===== STM32F407 RTC Clock =====\r\n");

    /* ===== User main loop ===== */
    while (1)
    {
        /* Note: must read Time before Date; HAL library requires fixed order to avoid time jitter */
        HAL_RTC_GetTime(&hrtc, &sTime, RTC_FORMAT_BIN);
        HAL_RTC_GetDate(&hrtc, &sDate, RTC_FORMAT_BIN);

        /* Print date and time: YYYY-MM-DD HH:MM:SS */
        printf("20%02d-%02d-%02d %02d:%02d:%02d\r\n",
               sDate.Year, sDate.Month, sDate.Date,
               sTime.Hours, sTime.Minutes, sTime.Seconds);

        HAL_Delay(PRINT_INTERVAL);
    }
}

void Error_Handler(void)
{
    while (1)
    {
    }
}

void SystemClock_Config(void)
{
    /* HSE 8MHz -> PLL -> 168MHz, generated by CubeMX */
}
