/*
 * Project: 05-adc-potentiometer ADC Potentiometer Sampling
 * Platform: STM32F407VET6
 * Frequency: 168 MHz
 * Library: HAL Library
 * Function: ADC1 IN0 (PA0) samples 10k potentiometer voltage, 12-bit resolution, prints raw value and converted voltage via USART1
 * Pin: Potentiometer wiper -> PA0, USART1 -> PA9/PA10
 * Note: This main.c shows user code only. CubeMX-generated initialization code (MX_*_Init) should be regenerated via CubeMX.
 */
#include "main.h"
#include "stm32f4xx_hal.h"
#include <stdio.h>

/* ===== External handle declarations (generated by CubeMX) ===== */
extern ADC_HandleTypeDef hadc1;
extern UART_HandleTypeDef huart1;

/* ===== User macro definitions ===== */
#define ADC_RESOLUTION_BITS 12                          /* 12-bit ADC */
#define ADC_MAX_VALUE     ((1 << ADC_RESOLUTION_BITS) - 1) /* 4095 */
#define VREF_VOLTAGE      3.3f                          /* Reference voltage 3.3V */
#define SAMPLE_INTERVAL   500                          /* Sampling interval (ms) */

/* ===== printf redirection ===== */
#ifdef __GNUC__
int __io_putchar(int ch)
#else
int fputc(int ch, FILE *f)
#endif
{
    HAL_UART_Transmit(&huart1, (uint8_t *)&ch, 1, HAL_MAX_DELAY);
    return ch;
}

/* ===== ADC single sampling function ===== */
/* Returns ADC raw value 0~4095 */
uint32_t ADC_Read(void)
{
    uint32_t value = 0;
    /* Start ADC conversion */
    HAL_ADC_Start(&hadc1);
    /* Poll for conversion completion */
    if (HAL_ADC_PollForConversion(&hadc1, HAL_MAX_DELAY) == HAL_OK)
    {
        value = HAL_ADC_GetValue(&hadc1);
    }
    /* Stop ADC */
    HAL_ADC_Stop(&hadc1);
    return value;
}

/* ===== Main function ===== */
int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_ADC1_Init();
    MX_USART1_UART_Init();

    /* Calibrate ADC (optional on F4) */
    printf("\r\n===== ADC Potentiometer Test =====\r\n");

    /* ===== User main loop ===== */
    while (1)
    {
        uint32_t adcValue = ADC_Read();
        /* Voltage conversion: voltage = raw value / 4095 * 3.3V */
        float voltage = (float)adcValue * VREF_VOLTAGE / (float)ADC_MAX_VALUE;
        printf("ADC: %4lu, Voltage: %.2f V\r\n", adcValue, voltage);
        HAL_Delay(SAMPLE_INTERVAL);
    }
}

void Error_Handler(void)
{
    while (1)
    {
    }
}

void SystemClock_Config(void)
{
    /* HSE 8MHz -> PLL -> 168MHz, generated by CubeMX */
}
