[platformio]
default_envs = stc89c52rc

[env:stc89c52rc]
platform = intel_mcs51
board = stc89c52rc
board_build.f_cpu = 11059200UL
build_flags = 
    -Wall
upload_protocol = stcgal
upload_port = COM3    ; 修改为实际串口
upload_speed = 9600
