[platformio]
default_envs = stm32f407vet6

[env:stm32f407vet6]
platform = ststm32
board = black_f407vg
board_build.mcu = stm32f407vet6
board_build.f_cpu = 168000000L
build_flags = 
    -D USE_HAL_DRIVER
    -D STM32F407xx
    -D HSE_VALUE=8000000
    -D configUSE_PREEMPTION=1
    -D configUSE_PORT_OPTIMISED_TASK_SELECTION=1
    -D configCPU_CLOCK_HZ=168000000
    -D configTICK_RATE_HZ=1000
    -u _printf_float
    -Wall
lib_deps = 
    STM32duino/STM32duino STM32HAL @ ^2.0.0
upload_protocol = stlink
debug_tool = stlink
