/*
 * Project: 01-hal-led-blink HAL LED Blink
 * Platform: STM32F407VET6
 * Frequency: 168 MHz
 * Library: HAL Library
 * Function: Toggle LED on PE0 every 500ms using HAL_GPIO_TogglePin and HAL_Delay
 * Pin: LED anode -> 220ohm current-limiting resistor -> PE0 -> GND
 * Note: This main.c shows user code only. CubeMX-generated initialization code (MX_*_Init) should be regenerated via CubeMX.
 */
#include "main.h"
#include "stm32f4xx_hal.h"
#include <stdio.h>

/* ===== User macro definitions ===== */
/* LED pin and port */
#define LED_PIN     GPIO_PIN_0
#define LED_PORT    GPIOE
/* Blink period (ms): 500ms on, 500ms off */
#define BLINK_DELAY 500

/* ===== External variable declarations (generated by CubeMX) ===== */
/* No external handle needed; this project uses GPIO only */

/* ===== Main function ===== */
int main(void)
{
    /* HAL library initialization (generated by CubeMX) */
    HAL_Init();

    /* System clock configured to 168MHz (generated by CubeMX) */
    SystemClock_Config();

    /* GPIO initialization: configure PE0 as push-pull output (generated by CubeMX) */
    MX_GPIO_Init();

    /* ===== User main loop ===== */
    while (1)
    {
        /* Toggle LED pin level: high->low or low->high */
        HAL_GPIO_TogglePin(LED_PORT, LED_PIN);

        /* Blocking delay 500ms */
        HAL_Delay(BLINK_DELAY);
    }
}

/* ===== HAL error callback (optional implementation) ===== */
void Error_Handler(void)
{
    /* Enter infinite loop; error indication can be added here */
    while (1)
    {
    }
}

/* ===== System clock configuration function (generated by CubeMX, placeholder here) ===== */
void SystemClock_Config(void)
{
    /* CubeMX will generate complete clock configuration code:
       HSE 8MHz -> PLL -> SYSCLK 168MHz
       AHB 168MHz / APB1 42MHz / APB2 84MHz
       Please regenerate this function via CubeMX */
}
