/*
 * Project: 03-timer-pwm Timer PWM
 * Platform: STM32F407VET6
 * Frequency: 168 MHz
 * Library: HAL Library
 * Function: TIM3 CH1 (PA6) outputs PWM with duty cycle 0-100% gradient to realize LED breathing effect
 * Pin: LED + 220ohm resistor -> PA6 (TIM3_CH1)
 * Note: This main.c shows user code only. CubeMX-generated initialization code (MX_*_Init) should be regenerated via CubeMX.
 */
#include "main.h"
#include "stm32f4xx_hal.h"
#include <stdio.h>

/* ===== External handle declarations (generated by CubeMX) ===== */
extern TIM_HandleTypeDef htim3;

/* ===== User macro definitions ===== */
/* PWM channel */
#define PWM_CHANNEL     TIM_CHANNEL_1
/* Duty cycle upper limit (ARR=1000, so duty = CCR/10) */
#define PWM_MAX         1000
/* Duty cycle step */
#define PWM_STEP        10
/* Gradient delay (ms) */
#define FADE_DELAY      20

/* ===== Main function ===== */
int main(void)
{
    /* HAL initialization */
    HAL_Init();
    /* Clock 168MHz */
    SystemClock_Config();
    /* GPIO and TIM3 initialization */
    MX_GPIO_Init();
    MX_TIM3_Init();

    /* Start TIM3 CH1 PWM output */
    HAL_TIM_PWM_Start(&htim3, PWM_CHANNEL);

    /* Current duty cycle (CCR value) */
    uint16_t duty = 0;
    /* Direction: 1=increment (brighten), 0=decrement (dim) */
    uint8_t direction = 1;

    /* ===== User main loop ===== */
    while (1)
    {
        /* Set CCR value to adjust duty cycle */
        __HAL_TIM_SET_COMPARE(&htim3, PWM_CHANNEL, duty);

        if (direction)
        {
            /* Brighten: increment duty cycle */
            duty += PWM_STEP;
            if (duty >= PWM_MAX)
            {
                duty = PWM_MAX;
                direction = 0;
            }
        }
        else
        {
            /* Dim: decrement duty cycle */
            if (duty >= PWM_STEP)
            {
                duty -= PWM_STEP;
            }
            if (duty == 0)
            {
                direction = 1;
            }
        }

        /* Gradient interval, controls breathing speed */
        HAL_Delay(FADE_DELAY);
    }
}

void Error_Handler(void)
{
    while (1)
    {
    }
}

void SystemClock_Config(void)
{
    /* HSE 8MHz -> PLL -> 168MHz, generated by CubeMX */
}
