/*
 * Project: 09-freertos-multitask FreeRTOS Multitask
 * Platform: STM32F407VET6
 * Frequency: 168 MHz
 * Library: HAL Library + CMSIS-RTOS v2
 * Function: Create 3 tasks - LED blink, button detection, UART print; demonstrate task scheduling and osDelay
 * Pin: LED -> PE0, Button -> PE4, USART1 -> PA9/PA10
 * Note: This main.c shows user code only. CubeMX-generated initialization code (MX_*_Init) should be regenerated via CubeMX.
 */
#include "main.h"
#include "stm32f4xx_hal.h"
#include "cmsis_os2.h"
#include <stdio.h>

/* ===== External handle declarations (generated by CubeMX) ===== */
extern UART_HandleTypeDef huart1;

/* ===== User macro definitions ===== */
#define LED_PIN     GPIO_PIN_0
#define LED_PORT    GPIOE
#define BUTTON_PIN  GPIO_PIN_4
#define BUTTON_PORT GPIOE

/* ===== Global shared variables ===== */
/* Button press count (shared across tasks; in real projects should be protected with a mutex) */
volatile uint32_t g_buttonCount = 0;

/* ===== printf redirection ===== */
#ifdef __GNUC__
int __io_putchar(int ch)
#else
int fputc(int ch, FILE *f)
#endif
{
    HAL_UART_Transmit(&huart1, (uint8_t *)&ch, 1, HAL_MAX_DELAY);
    return ch;
}

/* ===== Task 1: LED blink =====
 * Toggle LED every 500ms, demonstrates non-blocking osDelay
 */
void LEDTask(void *argument)
{
    (void)argument;
    while (1)
    {
        HAL_GPIO_TogglePin(LED_PORT, LED_PIN);
        /* osDelay yields CPU to other tasks, does not block scheduler */
        osDelay(500);
    }
}

/* ===== Task 2: Button detection =====
 * Poll PE4 button state, software debounce, increment count on press
 */
void ButtonTask(void *argument)
{
    (void)argument;
    uint8_t lastState = 1; /* Default pull-up gives high level */
    while (1)
    {
        uint8_t state = HAL_GPIO_ReadPin(BUTTON_PORT, BUTTON_PIN);
        /* Detect falling edge (press moment: high->low) */
        if (lastState == 1 && state == 0)
        {
            /* Software debounce: delay then read again */
            osDelay(20);
            if (HAL_GPIO_ReadPin(BUTTON_PORT, BUTTON_PIN) == 0)
            {
                g_buttonCount++;
            }
        }
        lastState = state;
        osDelay(10); /* 10ms polling period */
    }
}

/* ===== Task 3: UART print =====
 * Output button statistics every second
 */
void PrintTask(void *argument)
{
    (void)argument;
    uint32_t lastCount = 0;
    while (1)
    {
        printf("Button pressed: %lu times (total)\r\n", g_buttonCount);
        (void)lastCount;
        lastCount = g_buttonCount;
        osDelay(1000);
    }
}

/* ===== Main function ===== */
int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_USART1_UART_Init();

    /* Initialize LED to off */
    HAL_GPIO_WritePin(LED_PORT, LED_PIN, GPIO_PIN_RESET);

    printf("\r\n===== FreeRTOS Multitask Demo =====\r\n");

    /* ===== Initialize RTOS kernel ===== */
    osKernelInitialize();

    /* ===== Create tasks ===== */
    /* Task attribute struct (optional config of task name, stack size, priority) */
    osThreadAttr_t ledAttr = {
        .name = "LEDTask",
        .stack_size = 256,
        .priority = osPriorityNormal,
    };
    osThreadAttr_t btnAttr = {
        .name = "ButtonTask",
        .stack_size = 256,
        .priority = osPriorityNormal,
    };
    osThreadAttr_t printAttr = {
        .name = "PrintTask",
        .stack_size = 512,
        .priority = osPriorityBelowNormal,
    };

    osThreadNew(LEDTask, NULL, &ledAttr);
    osThreadNew(ButtonTask, NULL, &btnAttr);
    osThreadNew(PrintTask, NULL, &printAttr);

    /* ===== Start scheduler ===== */
    osKernelStart();

    /* Normally execution never reaches here */
    while (1)
    {
    }
}

void Error_Handler(void)
{
    while (1)
    {
    }
}

void SystemClock_Config(void)
{
    /* HSE 8MHz -> PLL -> 168MHz, generated by CubeMX
     * Note: after FreeRTOS is enabled, SysTick is occupied by RTOS,
     * HAL time base should use another timer (e.g. TIM1) */
}
