/*
 * Project: 06-spi-flash SPI Flash Read/Write
 * Platform: STM32F407VET6
 * Frequency: 168 MHz
 * Library: HAL Library
 * Function: SPI1 (PA5/PA6/PA7 + PB0 CS) reads/writes W25Q64: erase sector 0, write "Hello", read back and verify
 * Pin: SPI1 SCK-PA5, MISO-PA6, MOSI-PA7, CS-PB0
 * Note: This main.c shows user code only. CubeMX-generated initialization code (MX_*_Init) should be regenerated via CubeMX.
 */
#include "main.h"
#include "stm32f4xx_hal.h"
#include <stdio.h>
#include <string.h>

/* ===== External handle declarations (generated by CubeMX) ===== */
extern SPI_HandleTypeDef hspi1;
extern UART_HandleTypeDef huart1;

/* ===== W25Q64 chip-select control macros ===== */
#define W25Q_CS_LOW()   HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_RESET)
#define W25Q_CS_HIGH()  HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_SET)

/* ===== W25Q64 command definitions ===== */
#define W25Q_WRITE_ENABLE   0x06  /* Write enable */
#define W25Q_SECTOR_ERASE   0x20  /* 4KB sector erase */
#define W25Q_PAGE_PROGRAM   0x02  /* Page program (256 bytes/page) */
#define W25Q_READ_DATA      0x03  /* Read data */
#define W25Q_READ_STATUS    0x05  /* Read status register */

/* ===== printf redirection ===== */
#ifdef __GNUC__
int __io_putchar(int ch)
#else
int fputc(int ch, FILE *f)
#endif
{
    HAL_UART_Transmit(&huart1, (uint8_t *)&ch, 1, HAL_MAX_DELAY);
    return ch;
}

/* ===== W25Q64 low-level operation functions ===== */

/* Wait for Flash idle (BUSY bit cleared) */
void W25Q_WaitBusy(void)
{
    uint8_t status = 0;
    uint8_t cmd = W25Q_READ_STATUS;
    do
    {
        W25Q_CS_LOW();
        HAL_SPI_Transmit(&hspi1, &cmd, 1, HAL_MAX_DELAY);
        HAL_SPI_Receive(&hspi1, &status, 1, HAL_MAX_DELAY);
        W25Q_CS_HIGH();
    } while (status & 0x01); /* bit0 is BUSY bit */
}

/* Write enable */
void W25Q_WriteEnable(void)
{
    uint8_t cmd = W25Q_WRITE_ENABLE;
    W25Q_CS_LOW();
    HAL_SPI_Transmit(&hspi1, &cmd, 1, HAL_MAX_DELAY);
    W25Q_CS_HIGH();
}

/* Erase 4KB sector */
void W25Q_EraseSector(uint32_t addr)
{
    uint8_t cmd[4] = {
        W25Q_SECTOR_ERASE,
        (uint8_t)(addr >> 16),
        (uint8_t)(addr >> 8),
        (uint8_t)(addr)
    };
    W25Q_WriteEnable();
    W25Q_CS_LOW();
    HAL_SPI_Transmit(&hspi1, cmd, 4, HAL_MAX_DELAY);
    W25Q_CS_HIGH();
    W25Q_WaitBusy();
}

/* Page program write */
void W25Q_PageProgram(uint32_t addr, uint8_t *data, uint16_t len)
{
    uint8_t cmd[4] = {
        W25Q_PAGE_PROGRAM,
        (uint8_t)(addr >> 16),
        (uint8_t)(addr >> 8),
        (uint8_t)(addr)
    };
    W25Q_WriteEnable();
    W25Q_CS_LOW();
    HAL_SPI_Transmit(&hspi1, cmd, 4, HAL_MAX_DELAY);
    HAL_SPI_Transmit(&hspi1, data, len, HAL_MAX_DELAY);
    W25Q_CS_HIGH();
    W25Q_WaitBusy();
}

/* Read data */
void W25Q_ReadData(uint32_t addr, uint8_t *buf, uint16_t len)
{
    uint8_t cmd[4] = {
        W25Q_READ_DATA,
        (uint8_t)(addr >> 16),
        (uint8_t)(addr >> 8),
        (uint8_t)(addr)
    };
    W25Q_CS_LOW();
    HAL_SPI_Transmit(&hspi1, cmd, 4, HAL_MAX_DELAY);
    HAL_SPI_Receive(&hspi1, buf, len, HAL_MAX_DELAY);
    W25Q_CS_HIGH();
}

/* ===== Main function ===== */
int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_SPI1_Init();
    MX_USART1_UART_Init();

    /* CS initially pulled high (idle) */
    W25Q_CS_HIGH();
    HAL_Delay(100);

    printf("\r\n===== W25Q64 SPI Flash Test =====\r\n");

    uint8_t writeBuf[] = "Hello";
    uint8_t readBuf[16] = {0};
    uint16_t writeLen = sizeof(writeBuf);

    /* 1. Erase sector 0 */
    printf("Erasing sector 0...\r\n");
    W25Q_EraseSector(0x000000);

    /* 2. Write "Hello" */
    printf("Writing \"Hello\" to address 0x000000...\r\n");
    W25Q_PageProgram(0x000000, writeBuf, writeLen);

    /* 3. Read back and verify */
    printf("Reading back...\r\n");
    W25Q_ReadData(0x000000, readBuf, writeLen);
    printf("Read back: %s\r\n", readBuf);

    /* Verify */
    if (memcmp(writeBuf, readBuf, writeLen) == 0)
    {
        printf("[OK] Data verification passed!\r\n");
    }
    else
    {
        printf("[FAIL] Data verification failed!\r\n");
    }

    /* ===== User main loop ===== */
    while (1)
    {
        HAL_Delay(1000);
    }
}

void Error_Handler(void)
{
    while (1)
    {
    }
}

void SystemClock_Config(void)
{
    /* HSE 8MHz -> PLL -> 168MHz, generated by CubeMX */
}
